### ISSUE TITLE
on https://apps.fedoraproject.org/packages search for xorg-x11-drv-sis doesn't find xorg-x11-drv-sis

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fedora-packages#109]
xorg-x11-drv-sis doesn't appear in search :
https://apps.fedoraproject.org/packages/s/xorg-x11-drv-sis
xorg-x11-drv-sis was retired in F21 or F22 , but is not reason to not appear in search of packages

**Comment by ralphbean** [comment]
As things are written now, it has to be in rawhide (not retired there) in order to show up in the packages app.

This is a problem for epel-only compat packages.. so we're going to need to change that.

**Comment by sergiomb2** [comment]
Hi, 
Search in pkgdb [1] works great, packages should have the same results  , I don't know if it is possible .

[1] https://admin.fedoraproject.org/pkgdb/packages/xorg-x11-drv*/

**Comment by ralphbean** [comment]
That is a possibility.  As a point of history:  pkgdb2 didn't exist when fedora-packages was first written.

**Comment by sergiomb2** [comment]
Another issue for you to think about :
Searching for python-gammu , Fedora packages said that was a sub package of gammu , but also exist the package python-gammu  [1] , that is retired in devel and BTW, for me, the existence of the package was more important information.

Thanks,

[1] https://admin.fedoraproject.org/pkgdb/package/python-gammu/

**Comment by pypingou** [comment]
https://apps.fedoraproject.org/packages/python-gammu seems to be in packages now

**Comment by pypingou** [comment]
As for https://admin.fedoraproject.org/pkgdb/package/xorg-x11-drv-sis/ it's entirely retired so we cannot find it anywhere.

I think we can now close this bug.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
