### ISSUE TITLE
buglist don't show the current open bugs, it seems to be stuck somehow.

### ISSUE THREAD

**Issue by timlau** [fedora-infra/fedora-packages#116]
https://apps.fedoraproject.org/packages/yumex/bugs/all show 29 open bugs

https://bugzilla.redhat.com/buglist.cgi?cmdtype=runnamed&list_id=2894837&namedcmd=yumex
shows 15 open bugs

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
