### ISSUE TITLE
overview information out of date (cached too long?)

### ISSUE THREAD

**Issue by FelixSchwarz** [fedora-infra/fedora-packages#122]
The [vpnc page](https://apps.fedoraproject.org/packages/vpnc/overview/) does not display the latest versions on the overview page even after a couple of days. It's interesting though that the "history" section shows newer builds correctly (as well as the "builds" tab). Only the main version table is out of date.

As of now (2014-11-13) the correct releases for vpnc are (in testing):
F21               0.5.3-24.svn550.fc21  (displayed: None)
F20               0.5.3-21.svn550.fc20  (displayed: None)

This might be the same issue as #113 but I'm filing it anyway as it is on a separate page and also parts of the page content are up-to-date.

![vpnc-overview](https://cloud.githubusercontent.com/assets/212753/5025659/a99e1cac-6b1b-11e4-86aa-25b224480cb6.png)

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
