### ISSUE TITLE
EPEP-only package php-extras is not found

### ISSUE THREAD

**Issue by tyll** [fedora-infra/fedora-packages#130]
It is in pkgdb:
https://admin.fedoraproject.org/pkgdb/package/php-extras/

But the packages app does not find it:
https://apps.fedoraproject.org/packages/s/php-extras

**Comment by ralphbean** [comment]
It's been a while since I looked at it, but I think it only finds packages that are in rawhide.  Will leave this open to fix.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
