### ISSUE TITLE
Changelog page lists outdated info

### ISSUE THREAD

**Issue by techtonik** [fedora-infra/fedora-packages#136]
https://apps.fedoraproject.org/packages/gparted/changelog/

For 21 it lists 0.19.1-3.fc21, but the latest released version on https://apps.fedoraproject.org/packages/gparted/overview/ for 21 is 0.20.0-1.fc21

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.

**Comment by techtonik** [comment]
Nice diagrams. You could try using http://interactive.blockdiag.com/
