### ISSUE TITLE
"Sources" link on https://apps.fedoraproject.org/packages/cups/overview/ yields an "Oops! Something Went Wrong" if JavaScript is blacklisted 

### ISSUE THREAD

**Issue by shlomif** [fedora-infra/fedora-packages#141]
Hi all,

if I go to https://apps.fedoraproject.org/packages/cups/overview/ with Firefox with the NoScript extension ( https://noscript.net/ ) installed and set to blacklist JavaScript from all domains by default (with the ability to whitelist it), then if I click on the "Sources" link, then I get an "Oops! Something Went Wrong" / Radioactive Panda / 500 code error instead of something more meaningful. Please look into making it more user-friendly.

Otherwise, I should note that going to https://apps.fedoraproject.org/packages/cups/overview/ takes a very long time to load - in both Firefox with NoScript and in Google Chromium without it. I'm located in Tel Aviv, Israel and use Bezeq International as my ISP (ADSL).

Best regards,

-- Shlomi Fish

**Comment by pypingou** [comment]
The `Sources` tab of cups does not work at all for me and firebug shows:
``
"NetworkError: 500 Internal Server Error - https://apps.fedoraproject.org/packages/_w/package_sources?subpackage_of=&package_name=cups"
``
Which explains the 500 error code you're seeing, noscript is for nothing in there, there is most likely a problem.

Loading the overview page is also taking a while here.

**Comment by shlomif** [comment]
@pypingou : hi! Thanks for the insights in your comment.
