### ISSUE TITLE
information about packages in releases/updates is outdated

### ISSUE THREAD

**Issue by pavlix** [fedora-infra/fedora-packages#145]
When issuing Fedora updates, I realized that I don't see them updated in https://apps.fedoraproject.org/packages/ immediately nor after a while. Without current information, fedora-packages is not as useful as it could be.

**Comment by ralphbean** [comment]
Known issue.  :(

It gets updated by a *very* fragile cronjob.  It's on our list of [major goals](https://fedoraproject.org/wiki/Fedora_Engineering/FY16_Plan) for this year.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
