### ISSUE TITLE
package versions should link to koji build

### ISSUE THREAD

**Issue by pavlix** [fedora-infra/fedora-packages#146]
Some package versions listed in "packages" link to a bodhi update page while others aren't links at all. I think it would be a great improvement if all versions linked consistently to koji builds and those with updates had an additional link to bodhi.

It might also be useful to show which version of a package has been released originally with the respective Fedora release, as that information would give one a hint of a range of versions that can bee seen in an installation of that release of Fedora whether updated or not.

**Comment by ralphbean** [comment]
Agreed.  That would be cool.
