### ISSUE TITLE
New ceres-solver package not listed

### ISSUE THREAD

**Issue by nocnokneo** [fedora-infra/fedora-packages#147]
I am not able to find [ceres-solver](http://pkgs.fedoraproject.org/cgit/ceres-solver.git/) package at https://apps.fedoraproject.org/packages/

**Comment by nocnokneo** [comment]
It turns out to be a search bug: If I just search for `ceres` the package shows up. If I search for `ceres-solver` it does not.

**Comment by ralphbean** [comment]
Odd, it works for me now when I [search for ceres-solver](https://apps.fedoraproject.org/packages/s/ceres-solver).

**Comment by nocnokneo** [comment]
Looks like it's been fixed!

**Comment by ralphbean** [comment]
Thanks @nocnokneo :)
