### ISSUE TITLE
Fedora 21 up-to-date installation : missing mkiss module

### ISSUE THREAD

**Issue by UgoPoddine** [fedora-infra/fedora-packages#151]
Hello everyone,

just trying to setup the ax25 interface on a new Fedora21 system, clean and well running.
I have installed AX25-tools using YUM without any warning.
modprobe ax25 it's ok, the service starts as usual
modprobe mkiss returns the error "modprobe: FATAL: Module mkiss not found"
Of course any kissattach attempt returns the "Are you sure you have enabled MKISS support in the kernel" classic question...
Any suggestion ? Must I install by building from sources ?

Any help appreciated
73, Ugo

**Comment by pypingou** [comment]
I believe this is not the right place to report such issue.

This project is about the web application: https://apps.fedoraproject.org/packages/

For your issue you may want to try asking on https://ask.fedoraproject.org/ or report a bug at https://bugzilla.redhat.com
