### ISSUE TITLE
Gnome pie appears with black-boxed background in fedora 21

### ISSUE THREAD

**Issue by arcleise** [fedora-infra/fedora-packages#152]
As described in title, let me know what log do you need.

**Comment by nirik** [comment]
I think you are reporting this in the wrong place here. ;) 

This is for bugs with the Fedora Infrastructure "packages" application at https://apps.fedoraproject.org/packages/ 

While it does show information about gnome-pie, it doesn't have anything to do with the actual package. You want to report bugs on gnome-pie to: 

https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&version=rawhide&component=gnome-pie
