### ISSUE TITLE
Fedora Packages doesn't reflect same versions like Fedora Bodhi

### ISSUE THREAD

**Issue by robert-scheck** [fedora-infra/fedora-packages#153]
Just compare https://apps.fedoraproject.org/packages/prosody vs. https://admin.fedoraproject.org/updates/search/prosody - why does Fedora Packages still list the old versions and none of the updates in testing?

**Comment by marclaporte** [comment]
Looks like https://apps.fedoraproject.org/packages/prosody is now OK. Thanks!
