### ISSUE TITLE
DNF fails to install packages if any package is not available.

### ISSUE THREAD

**Issue by GittyUpTom** [fedora-infra/fedora-packages#154]
If a package in an install list doesn't exist, dnf fails to install any package.
eg:
[root@myplace ~]# dnf install espeak foo
Last metadata expiration check performed 2:52:58 ago on Fri May 22 08:49:02 2015.
No package foo available.
Error: no package matched: foo
[root@myplace ~]#

**Comment by Fale** [comment]
Sorry, this is not the place to report this kind of bug. This bug tracker is solely for the webinterface you can find at https://apps.fedoraproject.org/packages/

The bug you are experiencing should be reported to the [dnf bugtracker](https://bugzilla.redhat.com/buglist.cgi?component=DNF).
