### ISSUE TITLE
No results are returned when searching for "cmake28"

### ISSUE THREAD

**Issue by nocnokneo** [fedora-infra/fedora-packages#155]
The following search:

https://apps.fedoraproject.org/packages/s/cmake28

Should list the `cmake28` and `cmake28-gui` packages in EPEL6

**Comment by Fale** [comment]
cmake is not provided by EPEL repository since it's already in the official repository

**Comment by nocnokneo** [comment]
I'm talking about the `cmake28` package, not the `cmake` package.

**Comment by Fale** [comment]
sorry, my bad

**Comment by ralphbean** [comment]
Agreed.  The problem is that everything in the fedora-packages app assumes that the package exists in rawhide first, so we'll need to fix that.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.

**Comment by nocnokneo** [comment]
Great, thanks!
