### ISSUE TITLE
darktable doesn't start

### ISSUE THREAD

**Issue by HansVanpee** [fedora-infra/fedora-packages#157]
RAW processor darktable doesn't load anymore on FC22. It fails to load shared library libIlmImf-Imf_2_1.so.21 (cannot open shared object file: No such file or directory).

**Comment by pypingou** [comment]
Sorry, this is not the place to report this kind of bug. This bug tracker is solely for the webinterface you can find at https://apps.fedoraproject.org/packages/

The bug you are experiencing should be reported on the bugzilla: https://bugzilla.redhat.com
