### ISSUE TITLE
Default application for MATE

### ISSUE THREAD

**Issue by dschwoerer** [fedora-infra/fedora-packages#158]
I installed Fedora 21 MATE
/usr/share/applications/defaults.list only list gnome application.
It would be nice if the default application would be matched with the installed desktop.
This is especially annoying as most of the linked application are not installed.

**Comment by pypingou** [comment]
Sorry, this is not the place to report this kind of bug. This bug tracker is solely for the webinterface you can find at https://apps.fedoraproject.org/packages/

The problem you are experiencing should be reported on the bugzilla: https://bugzilla.redhat.com

**Comment by dschwoerer** [comment]
I am sorry.
It would be helpful if at the bottom of e.g. this page:
https://apps.fedoraproject.org/packages/shared-mime-info/bugs/
Instead of 'Found a bug?' It would mention 'Found a bug in the web interface?' - I guess that would have prevented my mistake.

**Comment by pypingou** [comment]
Thanks for the idea :)

@ralphbean this might be worth considering :)

**Comment by ralphbean** [comment]
:+1:
