### ISSUE TITLE
Package lucene++, not related info shown

### ISSUE THREAD

**Issue by c72578** [fedora-infra/fedora-packages#159]
This issue report refers to the following package/address:
https://apps.fedoraproject.org/packages/lucene++/

When you click on the following entries, unexpected and not related info is shown:
Builds, Contents, Changelog.

- Builds: Viewing 1-10 of 641786 builds

- Changelog:
0:4.10.3-1
    - Update to upstream 4.10.3. Alexander Kurtakov <akurtako@redhat.com> 06 Jan 2015
etc.
But this is not related to the lucene++ package, which is currently LATEST BUILD 3.0.7-1.fc23

**Comment by c72578** [comment]
![fedora_packages_lucene _builds](https://cloud.githubusercontent.com/assets/371551/8005111/b0e75daa-0b86-11e5-9151-7508782cdbdc.png)
![fedora_packages_lucene _changelog](https://cloud.githubusercontent.com/assets/371551/8005113/b47e07ac-0b86-11e5-95d5-660513b73d14.png)

**Comment by ralphbean** [comment]
This is likely an issue with the xapian search interface used internally to keep track of all the builds.  It is probably doing a query for ``lucene++``, but the ``++`` part probably has some xapian semantics and they need to be escaped.
