### ISSUE TITLE
search should give all results of pkgdb

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fedora-packages#160]
Example gdesklets [1] why link for bug reports [2] doesn't work ? 

[1] https://admin.fedoraproject.org/pkgdb/package/gdesklets/ 
[2] https://apps.fedoraproject.org/packages/gdesklets/bugs

search doesn't find recently retired packages why ?

**Comment by ralphbean** [comment]
Because this /packages/ app is written to only know about packages that have a rawhide build completed for them.  It has a cronjob that pulls in those new rawhide builds, but it is error prone and often misses them.

We're going to rewrite it.

**Comment by sergiomb2** [comment]
See Also: #109

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
