### ISSUE TITLE
New upstream location of google-noto-fonts

### ISSUE THREAD

**Issue by brawer** [fedora-infra/fedora-packages#161]
Dear Fedora maintainers,

currently, this page: https://apps.fedoraproject.org/packages/google-noto-fonts/overview/
lists the following as project homepage: https://code.google.com/p/noto

However, we recently moved from Google Code to GitHub; to cope with size limitations, we split the fonts over multiple repositories. The new locations are here:
https://github.com/googlei18n/noto-fonts
https://github.com/googlei18n/noto-cjk
https://github.com/googlei18n/noto-emoji

**Comment by ralphbean** [comment]
Thanks @brawer.  That value gets pulled from the ``URL`` field in the [rpm spec for Fedora](http://pkgs.fedoraproject.org/cgit/google-noto-fonts.git/tree/google-noto-fonts.spec#n17).  The maintainer there is @pravins.

**Comment by pravins** [comment]
I will take care of this. I have reported issue in bugzilla for same. https://bugzilla.redhat.com/show_bug.cgi?id=1269404
 Feel free to close this.

**Comment by pypingou** [comment]
Let's close then :)
