### ISSUE TITLE
dhclient fail in setting DHCP ipv6

### ISSUE THREAD

**Issue by Maulik1105** [fedora-infra/fedora-packages#162]
I am running my application on linux 3.10.17. To Configure dhcp ipv6 in my application I am using below mentioned command. Same command is getting executed in dhcp version 4.2.5-P1. But my application has dhclient version 4.3.0. And command cause failure for execution.
So Can any one guide me on this? What difference will be there in both version?

dhclient -6 -pf /var/run/udhcpc6.eth0.pid eth0 -e hostname:"ubuntu" -nw

Thanks in advance. Any help will be highly appreciable.

**Comment by pypingou** [comment]
Sorry, this is not the place to bring this kind of question. This bug tracker is solely for the webinterface you can find at https://apps.fedoraproject.org/packages/

Your question would likely be better suited on the forum: https://ask.fedoraproject.org/
