### ISSUE TITLE
List in "Latest released version" is not updated (even after a week)

### ISSUE THREAD

**Issue by lrineau** [fedora-infra/fedora-packages#163]
Currently in the [page for CGAL][cgal], we can read:
> LATEST BUILD
> 4.6.1-1.fc23

but in the section **Active Releases Overview**, we can read:
```
Release     Latest Released Version     Version in Testing
Rawhide     4.6-1.fc23                  None
Fedora 22   4.6-1.fc22                  4.6-1.fc22 0 karma
```

I understand that the application uses a cache, but the builds [CGAL-4.6.1-1.fc22][fc22] and [CGAL-4.6.1-1.fc23][fc23] are one week old. And the [update for CGAL-4.6.1-1.fc22][update] has been in testing for one week.

[cgal]: https://apps.fedoraproject.org/packages/CGAL
[fc22]: http://koji.fedoraproject.org/koji/buildinfo?buildID=666072
[fc23]: http://koji.fedoraproject.org/koji/buildinfo?buildID=666067
[update]: https://admin.fedoraproject.org/updates/FEDORA-2015-10960/CGAL-4.6.1-1.fc22

**Comment by lrineau** [comment]
See also #122, filled in Nov. 2014, that looks similar to my report.

**Comment by ralphbean** [comment]
This is likely some issue with the cronjob that pulls in new builds.  We're going to rewrite it.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
