### ISSUE TITLE
milter-greylist spf support request

### ISSUE THREAD

**Issue by deanbatten** [fedora-infra/fedora-packages#167]
# service milter-greylist start
...
> SPF support not compiled in,  ignore line 138
...

milter-greylist-4.5.12-2.el6.x86_64

**Comment by pypingou** [comment]
I am not sure to fully understand your report, which make me think it is not at its right place. This bug tracker is solely for the webinterface you can find at https://apps.fedoraproject.org/packages/

It seems to me that the problem you are experiencing should be reported on the bugzilla: https://bugzilla.redhat.com
