### ISSUE TITLE
Not active links in Package column

### ISSUE THREAD

**Issue by ganiuszka** [fedora-infra/fedora-packages#168]
Hello,

I noticed that links from 'Package' column do nothing independent on selected package.

Steps to reproduce:
1) https://apps.fedoraproject.org/packages/kernel-core/
2) Click on 'Builds' tab
3) Click on any 'kernel' link from 'Package' column.

The last click causes to add to URL "undefined/packages//" string for every click.

For example, after 3x click on kernel link, URL looks like below:
https://apps.fedoraproject.org/packages/kernel-core/undefined/packages//undefined/packages//undefined/packages//

Thank you in advance for help with this issue.

Best regards.
Marcin Haba (gani)

**Comment by ralphbean** [comment]
I started looking into it.. and I have no idea where that link was ever supposed to go.

**Comment by pypingou** [comment]
If it's koji maybe http://koji.fedoraproject.org/koji/search?type=package&match=glob&terms=kernel ?
