### ISSUE TITLE
apps web-site confused by some release numbers

### ISSUE THREAD

**Issue by PorcelainMouse** [fedora-infra/fedora-packages#169]
This may only be limited to the Firefox package, but I doubt it.  See here:

https://apps.fedoraproject.org/packages/firefox

It shows the latest update is 39.0-8, but the latest is actually 39.0.3-1.  With the recent spat of security updates, I've been checking this page a lot and it's confusing.

**Comment by ralphbean** [comment]
This is likely some issue with the cronjob that pulls in new builds from koji every 15 minutes.  It is prone to error and needs to be rewritten.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
