### ISSUE TITLE
Menu Issues

### ISSUE THREAD

**Issue by alleghenycomp** [fedora-infra/fedora-packages#171]
On Fedora 22 When KeePass is first opened it works fine.  However, open any other program while KeePass is open like Firefox and menu problems begin.  Drop down menus open but nothing is "clickable".  Close KeePass and reopen and it works again until you open something else.  Even trying to open everything you need prior to opening KeePass does not work as after a few minutes the menu's stop working right if other programs are open.  Worse yet and overtime of just trying to survive using "keyboard" commands they too begin doing things that were not intended.

I have confirmed this bug on all 10 of our local Fedora 22 workstations, both 64 & 32 bit as well as Intel and AMD based systems.

It appears the folks over at KeePass say this is a problem is either with how keepass or mono have been packaged.  In other words, it's always someone else's fault (SOP); go figure....

Any help would be greatly appreciated with resolving this bug as KeePass has become a very important program around here.

**Comment by laxathom** [comment]
Hmm, I think what you are looking for is to file a bug against keepass's rpm package and some input from the maintainers of this related package.

Thus, this is where you should start for reporting issue regarding a fedora package: https://fedoraproject.org/wiki/Bugs_and_feature_requests#The_Bugzilla_workflow

Hope, this will help you fix your issue.
