### ISSUE TITLE
Footer points to fedoracommunity

### ISSUE THREAD

**Issue by bochecha** [fedora-infra/fedora-packages#173]
In the footer of the [Fedora Packages home page](https://apps.fedoraproject.org/packages/), there is a link called "Get the source for Fedora Community Packages", pointing to: http://fedoracommunity.fedorahosted.org/

That doesn't seem like the same app. :smiley:

**Comment by ralphbean** [comment]
Heh :grin: will fix.  Thanks!

**Comment by ralphbean** [comment]
This was fixed in 2635e08d0c18c7ded67e01cce0c1387941da2599
