### ISSUE TITLE
Server does not support PLAIN

### ISSUE THREAD

**Issue by cookieofbliss** [fedora-infra/fedora-packages#174]
Unfortunately, the fedora gnome-online-accounts 3.16.3-1.fc22 does not support PLAIN authentification. This should be fixed (see https://git.gnome.org/browse/gnome-online-accounts/commit/?id=8da87488477b8a8b94cdba406bc2bea5f487860a) and in the goaimapsmtpprovider.c it should be supported.

(Came to this site by the link of the footer: https://apps.fedoraproject.org/packages/gnome-online-accounts/builds/)

**Comment by puiterwijk** [comment]
Please note that this service is just an aggregator. For bugs against packages, please file a bug in https://bugzilla.redhat.com/ against the Fedora product.
