### ISSUE TITLE
Missing new packages

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/fedora-packages#177]
It seems no more refresh happen on https://apps.fedoraproject.org/packages/  :(

Package imported in fedora >2 weeks ago are still not found (ex php-smbclient)

**Comment by ralphbean** [comment]
Yeah, it's super broken.  Our team has it slated [to be worked on in Q3](https://fedoraproject.org/wiki/Fedora_Engineering/FY16_Plan), but we haven't gotten a chance to start on it yet.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
