### ISSUE TITLE
apps.fp.o fails for package name "memtest86+"

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/fedora-packages#190]
Steps to reproduce:
1. Search for memtest
2. click on the link for "memtest86+"

What happens:
You will be redirected to the search as if you were searching for "memtest86+".

What is expected to happen:
Go to the package page.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
