### ISSUE TITLE
packages app seems to be out of sync with repository

### ISSUE THREAD

**Issue by nonamedotc** [fedora-infra/fedora-packages#192]
If I search for owncloud-client, all I see is mirall (see scrrenshot). This package has been renamed to owncloud-client.

See image here - http://imgur.com/TtUeYQ6

**Comment by ralphbean** [comment]
Yeah, it is definitely out of sync.  I'm working on a major rewrite of some backend bits.. which should hopefully be all deployed by the end of November.

**Comment by ralphbean** [comment]
OK, [that rewrite is deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
