### ISSUE TITLE
dnf-plugin-system-upgrade is missing from https://apps.fedoraproject.org/packages/

### ISSUE THREAD

**Issue by keszybz** [fedora-infra/fedora-packages#193]
https://apps.fedoraproject.org/packages/s/dnf-plugin-system-upgrade returns "0 results". The package is about a month old, so it cannot be a caching issue.

**Comment by ralphbean** [comment]
Yeah, the backend updating system is broken.  We're in the middle of a rewrite of much of it right now which should hopefully be deployed by the end of November.

**Comment by keszybz** [comment]
Ah, OK. I'll close this then and be patient.
