### ISSUE TITLE
gap-pkg-grape-4.6.1-1 has bugs in its GRAPE/bliss interface

### ISSUE THREAD

**Issue by lhsoicher** [fedora-infra/fedora-packages#196]
This new package released and maintained by jjames is meant to allow users to use my upstream GRAPE package with bliss instead of nauty, as nauty is excluded from Fedora for license reasons. However, there are bugs in its GRAPE/bliss interface. In particular, incorrect automorphism groups of graphs can be returned, and the vertex colouring of graphs is incorrectly output to bliss, leading to many more errors for automorphism groups and canonical labellings of graphs coloured with more than one vertex-colour. I have sent jjames corrections to these bugs. These corrections are implemented in the attached file meant to replace the package file /usr/lib/gap/pkg/grape/lib/grape.g
[grape.g.fix.txt](https://github.com/fedora-infra/fedora-packages/files/31900/grape.g.fix.txt)

**Comment by pypingou** [comment]
I fear your bug report is at the wrong location. This project is aimed at the website running at: https://apps.fedoraproject.org/packages

Your report would be better placed at https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&version=rawhide&component=bliss (if I understood you correctly and your fix applies to the package``bliss``)
