### ISSUE TITLE
Please update avrdude to 6.2

### ISSUE THREAD

**Issue by randyperkins** [fedora-infra/fedora-packages#198]
Hello
avrdude 6.2 has just been released.  How do I go about getting Fedora to start using this updated version of avrdude ?
http://lists.nongnu.org/archive/html/avrdude-dev/2015-11/msg00015.html

the previous versions of the 6.x series of avrdude had a bug where a usbasp programmer would fail when programming a M64 or M128 processor.

- bug #41561: AVRDUDE 6.0.1/USBasp doesn't write first bytes of
                  flash page

https://savannah.nongnu.org/bugs/?41561

If there is anything I can do to assist in this , please let me know

thanks

**Comment by pypingou** [comment]
This github project is for the web application running at: https://apps.fedoraproject.org/packages

For your question, I would encourage you to open a bug report at: https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&version=rawhide&component=avrdude

Thanks
