### ISSUE TITLE
Drop rhel5 mentions in footer

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fedora-packages#205]
https://apps.fedoraproject.org/packages/ has in the footer: 

"Found a bug? File a ticket. Note: There's some caching going on here. If you expect something and don't see it, check back in 5 minutes.
This Web Site is licensed under the GNU Affero General Public License. You may get sources for the current running code from these repositories:
Trademark GuidelinesGet the source for Fedora PackagesGet the source for MokshaRHEL5 Testing SRPMSRHEL6 Testing SRPMSRHEL5 Production SRPMSRHEL6 Production SRPMS"

We no longer run RHEL5, so perhaps we should drop all those links?

**Comment by ralphbean** [comment]
Agreed!
