### ISSUE TITLE
Ruby is not subpackage of Rubygems

### ISSUE THREAD

**Issue by voxik** [fedora-infra/fedora-packages#210]
This was originally discussed on Fedora's infrastructure list, but I am unable to link the discussion, since the Mailman/HyperKitty looks to be broken :/ Anyway, I'm pasting the original discussion here:

Dne 23.11.2015 v 16:55 Pierre-Yves Chibon napsal(a):

> On Mon, Nov 23, 2015 at 04:20:32PM +0100, Vít Ondruch wrote:
> 
> > Sorry, but I'm not really sure it works as expected looking at:
> > 
> > https://apps.fedoraproject.org/packages/ruby
> > 
> > it says "ruby - subpackage of rubygems" which is definitely not true.
> > So the data in mdapi seems correct:
> > https://apps.fedoraproject.org/mdapi/rawhide/pkg/rubygems?pretty=True
> > the basename is ruby, and rubygem is a sub-package of it.

Well, it is probably a bit more complex, considering this:

https://koji.fedoraproject.org/koji/buildinfo?buildID=682005
https://koji.fedoraproject.org/koji/buildinfo?buildID=674190

I.e. there is rubygems-2.4.5-44.fc24.noarch.rpm subpackage of ruby
package and at the same time rubygems-2.4.8-100.fc24.noarch.rpm, which
is standalone rubygems package. So if the mdapi is supposed to return
information about the latest package, the it should return information
about the rubygems-2.4.8-100.fc24.noarch.rpm, since it has higher NVR.

But that is probably different issue then the aforementioned one 

Vít

**Comment by pypingou** [comment]
So looking at the rawhide-primary DB, there are indeed two rubygems package and mdapi basically returns the first one found.

I've got to ask, why do we have two rubygems in the first place? I know pkgdb wouldn't allow it. This works because one of them is a subpackage, but are they actually different packages with the same name or just different versions of the same package ?

**Comment by voxik** [comment]
rubygems is not the only "overlapped" package in Fedora. There are several other rubygem- packages and as far as I know, there are also some perl- packages like this.

And of course, this allows us to update RubyGems independently of Ruby release, since RubyGems has faster release cycle than Ruby.

BTW this is nothing new. It works like this for past several years.

**Comment by pypingou** [comment]
But then what is the interest of keeping the sub-package rubygems?

I'm not saying this is new in general but it is certainly new to me :) (and I'm not sure I see the point of keeping the two of them).

**Comment by voxik** [comment]
Bootstrapping of new Ruby version and bootstrapping in general. And of course the ruby package is more universal, you can build older or newer version of Ruby in copr without building independent rubygems package.

**Comment by pypingou** [comment]
Is there already a bootstrapping flag in the ruby spec?
If so maybe building the rubygems sub-package could be either the same flag or another.
What do you think?

Note: while this would likely solve the issue for now, I do think we could also improve the situation for mdapi.

**Comment by voxik** [comment]
No, there is no boostrapping flag in ruby, since ruby is self-contained and updated rubygems is bonus.

I really believe that mdapi and all our tools should handle this situation correctly. There is no reason for whatever YUM/DNF repository to *not* contain more than one version of some package (look at Copr for example). And what is the source of that package is completely irrelevant.

**Comment by pypingou** [comment]
@ralphbean so I see two ways to go about this:

- Add a sorting by epoch, version, release and return the one with the highest evr
- Return all the packages of this name, which means breaking the API/backward compatibility.

What do you think?

**Comment by pypingou** [comment]
(I have the code ready for the first solution)

**Comment by voxik** [comment]
I am not @ralphbean, but the first solution seems natural to me ;)

**Comment by ralphbean** [comment]
I am @ralphbean and option 1 sounds good to me too.  ;)

**Comment by pypingou** [comment]
Implemented in https://pagure.io/mdapi/pull-request/25

**Comment by voxik** [comment]
Ping? Any progress? I was confused by bitten by this today again ...

**Comment by ralphbean** [comment]
If the mdapi change linked to above has been merged and deployed, then we may only need to rebuild the fedora-packages index for it to take effect.

**Comment by pypingou** [comment]
https://apps.stg.fedoraproject.org/mdapi/rawhide/pkg/ruby 
``"basename": "ruby",``

https://apps.stg.fedoraproject.org/mdapi/rawhide/pkg/rubygems
``"basename": "ruby",``

**Comment by ralphbean** [comment]
Help me out @pypingou - what does that mean?

**Comment by pypingou** [comment]
Sorry, just edited the comment to be a bit more descriptive :)

**Comment by pypingou** [comment]
Considering that rubygems is at 2.4.8-101 : http://pkgs.fedoraproject.org/cgit/rpms/rubygems.git/commit/
and ruby provides a bundled rubygems of version 2.5.1 : http://pkgs.fedoraproject.org/cgit/rpms/ruby.git/tree/ruby.spec#n32

It seems mdapi is behaving as desired

**Comment by ralphbean** [comment]
Cool.  Thank you :)

**Comment by voxik** [comment]
Reading the whole thread once more, I have strange feeling about it.

So packages asks mdapi for information about 'rubygems' package and it returns information about the most recent version. So far, that is just fine.

Does it mean that depending on current state of Fedora, the packages application will state that it is subpackage or it is not subpackage and depending on this, it will list BZ issues either for rubygems package or for ruby package? That sounds awkward.

**Comment by voxik** [comment]
Ping? Any update? Packages still claims that "ruby is subpackage of rubygems", which is not true under any condition.

**Comment by cverna** [comment]
@voxik I believe this will be fixed in the next release of fedora-packages. We have successfully managed  to deploy it to stg so it should arrive in prod soon.

You can check it here https://apps.stg.fedoraproject.org/packages/s/ruby

**Comment by voxik** [comment]
@cverna Nice! Thx.

BTW I just noticed that the "ruby in other apps" dropbox references PkgDB. This should be probably removed ...

**Comment by pypingou** [comment]
It's fixed in https://github.com/fedora-infra/fedora-packages/pull/314 :)

**Comment by cverna** [comment]
This is now fixed and deployed in production
