### ISSUE TITLE
bodhi-client does not show up in search results

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/fedora-packages#211]
In Fedora 23 there is a package named bodhi-client. It is not listed on apps.fp.o. Searching for it returns no results. Browsing to https://apps.fedoraproject.org/packages/bodhi-client redirects to the search.

**Comment by pypingou** [comment]
FTR it seems to be present in mdapi:
https://apps.fedoraproject.org/mdapi/f23/pkg/bodhi-client?pretty=True

**Comment by genodeftest** [comment]
eclipse-platform and eclipse-swt are missing too.

**Comment by tomhughes** [comment]
Yes #192 does not seem to be completely fixed. The historic missing ones have appeared I think but new ones created since are still not appearing, eg osmium-tool.

**Comment by fedpop** [comment]
my app mumble doesn't show up either. before I thought it didn't show up because it was orphaned but now it's been unretired for about a week and it doesn't show.

**Comment by ralphbean** [comment]
Thanks for being patient here everyone.  Note that mumble does show up now.

I'm not sure why bodhi-client isn't showing up though.

**Comment by tomhughes** [comment]
The reason bodhi-client isn't showing up is that it's a subpackage of bodhi, not a separate package.

**Comment by ralphbean** [comment]
Ah, but if I [search for policycoreutils-restorecond](https://apps.fedoraproject.org/packages/s/policycoreutils-restorecond), it works (and it should work...).

**Comment by genodeftest** [comment]
@tomhughes: should subpackages not be found?

**Comment by ralphbean** [comment]
imho, they should be found.

**Comment by tomhughes** [comment]
I just didn't realise that the search interface was supposed to find the subpackages. I normally just type the package name in `/packages/name` type URL which only works with the main package.

**Comment by cverna** [comment]
This is now fixed by the latest version deployed in production
