### ISSUE TITLE
[RFE] Let me open ticket no matter if I can retrieve information from BZ or not

### ISSUE THREAD

**Issue by voxik** [fedora-infra/fedora-packages#213]
Opening bug information page for some package (dnf in this case [1]), it should be immediately possible to open ticket for that package without waiting for refresh of information from BZ. The BZ link for the package is statis if I am not mistaken.

[1] https://apps.fedoraproject.org/packages/dnf/bugs

**Comment by pypingou** [comment]
We should be able to achieve this by reducing the width of the overlay to 250px instead of 750px, on that page.

**Comment by TridevGuha** [comment]
@pypingou can you give me the link on which page overlay need to be edited? please

**Comment by pypingou** [comment]
isn't it just above in the first comment?

**Comment by TridevGuha** [comment]
i mean there is no edit option in https://apps.fedoraproject.org/packages/dnf/bugs other than view page source

**Comment by aymanbagabas** [comment]
Not reproducible. I guess it's been resolved.

**Comment by voxik** [comment]
Yep, it was probably resovled. I can click on  "File new Bug" > "Fedora" right away.
