### ISSUE TITLE
letsencrypt does not show up

### ISSUE THREAD

**Issue by Fale** [fedora-infra/fedora-packages#216]
Searching for letsencrypt no results are returned [0] while in the package db it is present [1]

[0] https://apps.fedoraproject.org/packages/s/letsencrypt
[1] https://admin.fedoraproject.org/pkgdb/package/rpms/letsencrypt/

**Comment by ralphbean** [comment]
Thanks @fale.  It is there now.  Still working on the kinks in this latest rewrite.  Please keep filing bugs like this when you notice them.  It is very helpful.
