### ISSUE TITLE
subpackages of pygobject3 are not listed

### ISSUE THREAD

**Issue by csonto** [fedora-infra/fedora-packages#223]
I was searching for python3 bindings for gobject.
Nothing found.
Search for "python3-gobject" returns nothing too.

Not sure if this is the same as issue #215.

**Comment by pypingou** [comment]
Note that it is in mdapi: https://apps.fedoraproject.org/mdapi/rawhide/pkg/python3-gobject

**Comment by cverna** [comment]
This is fixed in the latest version deployed in production.
