### ISSUE TITLE
Xiphos-gtk3 won't update - "Requires: libsword-1.7.3.so"

### ISSUE THREAD

**Issue by jlj2** [fedora-infra/fedora-packages#226]
Yum update suggested updates to three packages c. 3 days ago on my Centos 7 system with epel 7 enabled by default (epel-testing not enabled;  priorities and protectbase plugins enabled):  xiphos, enca and sword.  When accepting update, a dependency problem was immediately reported, so I didn't update system then.  The dependency problem report was similar to the one I obtain today:
<addr> Resolving Dependencies
--> Running transaction check
---> Package enca.x86_64 0:1.16-1.el7 will be updated
---> Package enca.x86_64 0:1.18-1.el7 will be an update
---> Package sword.x86_64 0:1.7.3-9.el7 will be updated
--> Processing Dependency: libsword-1.7.3.so()(64bit) for package: xiphos-gtk3-4.0.4-3.el7.x86_64
---> Package sword.x86_64 0:1.7.4-6.el7 will be an update
---> Package xiphos-common.x86_64 0:4.0.3-1.el7 will be updated
---> Package xiphos-common.x86_64 0:4.0.4-3.el7 will be an update
---> Package xiphos-gtk3.x86_64 0:4.0.3-1.el7 will be updated
---> Package xiphos-gtk3.x86_64 0:4.0.4-3.el7 will be an update
--> Processing Dependency: libsword-1.7.3.so()(64bit) for package: xiphos-gtk3-4.0.4-3.el7.x86_64
--> Finished Dependency Resolution
Error: Package: xiphos-gtk3-4.0.4-3.el7.x86_64 (epel)
           Requires: libsword-1.7.3.so()(64bit)
           Removing: sword-1.7.3-9.el7.x86_64 (@epel)
               libsword-1.7.3.so()(64bit)
           Updated By: sword-1.7.4-6.el7.x86_64 (epel)
              Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
<addr>

Having uninstalled xiphos-gtk3 as a first step to attempt to update the system today, I was then able to only update enca and sword.  When attempting to reinstall xiphos:

<addr> Resolving Dependencies
--> Running transaction check
---> Package xiphos-gtk3.x86_64 0:4.0.4-3.el7 will be installed
--> Processing Dependency: libsword-1.7.3.so()(64bit) for package: xiphos-gtk3-4.0.4-3.el7.x86_64
--> Finished Dependency Resolution
Error: Package: xiphos-gtk3-4.0.4-3.el7.x86_64 (epel)
           Requires: libsword-1.7.3.so()(64bit)
<addr>

The following was to no avail:
<addr> yum clean all
yum check
yum erase apf     #but found that no apf installed
yum upgrade <addr>

If my observation is correct, I believe I noticed that either enca or sword installed a different version of libsword:  libsword-1.7.4.so.

**Comment by pypingou** [comment]
This is the wrong place for your report, this project is about the web application: https://apps.fedoraproject.org/packages.

You probably want to report your issue on https:/bugzilla.redhat.com and you can find links to it at: https://apps.fedoraproject.org/packages/xiphos/
