### ISSUE TITLE
libva-vdpau-driver-0.7.4-13.fc23.x86_64.rpm

### ISSUE THREAD

**Issue by Temujin0** [fedora-infra/fedora-packages#231]
getting video artefacts in all video vlc, html5 video, video player also with this package I cant seek through a html5 video. It hangs.I downgraded to libva-vdpau-driver-0.7.4-12.fc23.x86_64.rpm and my system went back to normal playback. This was the only package that was updated during an update. If I can provide any other info please let me know

**Comment by pypingou** [comment]
Thanks for your interest in Fedora but this is the wrong place to report a bug, unless it concerns the web application running at : https://apps.fedoraproject.org/packages/

If you wish to report a bug againsy liba-vdpau-driver you can find links to do so at: https://apps.fedoraproject.org/packages/libva-vdpau-driver/

**Comment by Temujin0** [comment]
Sorry about posting in the wrong place.Also thanks for pointing me in the right direction. i don't quite know my way around yet.
