### ISSUE TITLE
liferea's entry does not have a project homepage

### ISSUE THREAD

**Issue by eseyman** [fedora-infra/fedora-packages#233]
Liferea has an entry in the packages application: https://apps.fedoraproject.org/packages/liferea
but this entry has a "Project Homepage" entry: Unknown

Liferea's homepage is http://lzone.de/liferea/ and this information has being in the spec file for years now so I don't know why this information is not present in packages

**Comment by genodeftest** [comment]
URL is present in SPEC file, so this is an issue in parsing package metadata. An URL has been there even in 2010, so this can't be due to a "recent change": https://pkgs.fedoraproject.org/cgit/rpms/liferea.git/commit/?id=6c81d8e36801a7f4129cf2887bcc7314546cd250&context=10&ignorews=0&dt=0

**Comment by cverna** [comment]
This should be fix by #326.

**Comment by genodeftest** [comment]
This bug has been fixed in production.
