### ISSUE TITLE
Lmod packages prevent the correct function of `module use`, upon further bash invocations

### ISSUE THREAD

**Issue by fgeorgatos** [fedora-infra/fedora-packages#235]
```
echo 'export MODULEPATH=%{_sysconfdir}/modulefiles:%{_datadir}/modulefiles:%{_datadir}/Modules/modulefiles' > %{buildroot}%{_sysconfdir}/profile.d/00-modulepath.sh
echo 'setenv MODULEPATH %{_sysconfdir}/modulefiles:%{_datadir}/modulefiles:%{_datadir}/Modules/modulefiles' > %{buildroot}%{_sysconfdir}/profile.d/00-modulepath.csh
```

basically, the solution to this would be to use a guard variable, similar to what is described here:
http://lmod.readthedocs.org/en/latest/045_transition.html#an-example-of-how-this-can-be-done-in-your-bash-startup-scripts

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com

**Comment by fgeorgatos** [comment]
yes, understood and did that already - thanks ;-)

On 11 April 2016 at 20:47, Pierre-Yves Chibon <notifications@github.com>
wrote:

> Thanks for your report but this is however, the wrong place for such bug
> report.
>
> This issue tracker is about the web application running at:
> https://apps.fedoraproject.org/packages/
>
> Your ticket should be open in https://bugzilla.redhat.com
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fedora-infra/fedora-packages/issues/235#issuecomment-208525500>
>



-- 
echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum
