### ISSUE TITLE
mosqutto package only includes daemon, not clients/libs

### ISSUE THREAD

**Issue by karlp** [fedora-infra/fedora-packages#236]
somehow there's a mosquitto and mosquitto-devel package, but no client or libs packages.  Please create mosquitto-clients and libmosquitto(-devel) packages, as used to exist in the http://download.opensuse.org/repositories/home:/oojah:/mqtt/Fedora_22/home:oojah:mqtt.repo repo.

**Comment by puiterwijk** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com

**Comment by karlp** [comment]
Followed the link from https://apps.fedoraproject.org/packages/mosquitto/bugs  Perhaps I should file a bug saying, "no links to the right place to file bugs?"

**Comment by pypingou** [comment]
Well, this page has two big buttons saying: ``Open A New Bug (Fedora)`` and ``Open A New Bug (EPEL)``

**Comment by karlp** [comment]
I could swear they either weren't there, or their design made them completely inobvious to me, maybe triggered the useless banner add filter or something
