### ISSUE TITLE
per package bugs page has no link to file bugs

### ISSUE THREAD

**Issue by karlp** [fedora-infra/fedora-packages#238]
The per package bugs page, for instance https://apps.fedoraproject.org/packages/mosquitto/bugs has no link to create bugs in the "right" place, but _does_ include a link saying, "Found a bug? File a ticket"  While that link is probably still useful, an actual link to the real true source of the _package_ bugs would be very helpful, and avoid the mistakes of people filing bugs here.

**Comment by puiterwijk** [comment]
There are two buttons with "Open a new bug (Feodra)" and "Open a new bug (EPEL)" you can press.
A PR to update the footer link is in #237

**Comment by karlp** [comment]
blindness issues (possibly page design, but we'll call it user error)
