### ISSUE TITLE
glibc-langpack-xx doesn't show up in a.fp.o

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/fedora-packages#239]
https://apps.fedoraproject.org/packages/glibc doesn't list the glibc langpacks like glibc-langpack-aa and all the other langpacks. They are provided in [glibc's spec file](https://pkgs.fedoraproject.org/cgit/rpms/glibc.git/tree/glibc.spec#n564) but don't show up here.

**Comment by cverna** [comment]
This is fixed in the latest version deployed in production
