### ISSUE TITLE
B35 ForceRecon 3327S notebook touchpad not working

### ISSUE THREAD

**Issue by lees0088** [fedora-infra/fedora-packages#240]
Touchpad not working. In live user, before installing to HDD, it was working. Kindly help to check and advise. Attached are the general information. There is no Xorg log.

On windows 10, touchpad is working, elan touch device.

[dmesg.txt](https://github.com/fedora-infra/fedora-packages/files/276273/dmesg.txt)
[devices.txt](https://github.com/fedora-infra/fedora-packages/files/276274/devices.txt)

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
