### ISSUE TITLE
yaz package has disappeared from epel7

### ISSUE THREAD

**Issue by lumentouch** [fedora-infra/fedora-packages#241]
The yaz package seems to be missing from the EPEL7 repo.  It was present before but is not found now.

**Comment by lmacken** [comment]
This github issue tracker is for the fedora-packages project, seen here: https://apps.fedoraproject.org/packages/yaz/overview/

It confirms that `yaz` is unavailable in `epel7` -- so could you please file a new Bugzilla against Fedora EPEL for this component? Thanks! 

https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL&version=el6&component=yaz
