### ISSUE TITLE
copy-paste stop working

### ISSUE THREAD

**Issue by Dzurillo** [fedora-infra/fedora-packages#243]
Hi All!
After upgrade to Fedora24 (remmina-1.2.0-0.13.rcgit.7.fc24.x86_64) remmina's copy-paste clipboard between machines stop working
Thanks.

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
