### ISSUE TITLE
vtk-data package contains broken links to objects

### ISSUE THREAD

**Issue by theg4sh** [fedora-infra/fedora-packages#244]
Package vtk-data contains broken links to files in build directory of VTK, instead an original files.

E.g.
# ls -lah /usr/share/vtkdata/Testing/Data/
...
track3.binary.vtk -> /builddir/build/BUILD/VTK-6.2.0/.ExternalData/MD5/b4af0a0e3927b0ad845efe86c3c56889
...

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
