### ISSUE TITLE
missing /etc/ocamlfind.conf when Frama-C run

### ISSUE THREAD

**Issue by alx-pl** [fedora-infra/fedora-packages#245]
Once I installed Frama-C on Fedora-24 XFCE and run the program on my Fedora box I got the message

         Unexpected error (Failure("Config file not found - neither
/etc/ocamlfind.conf nor the directory /etc/ocamlfind.conf.d")).
         Please report as 'crash' at http://bts.frama-c.com/.
         Your Frama-C version is Aluminium-20160501.
         Note that a version and a backtrace alone often do not contain enough
         information to understand the bug. Guidelines for reporting bugs are

This message disappeared when I installed separately 

ocaml-findlib-1.5.5-8.fc24.x86_64

Apparently something was wrong with the dependencies of Frama-C at that point of the time as

ocaml-findlib-devel

is in the dependencies of Frama-C: 

https://apps.fedoraproject.org/packages/frama-c/sources/spec/

Still, the actual dependencies obtained as

> rpm -qR frama-c 

are silent about ocaml-findlib (see attachment).

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com

**Comment by alx-pl** [comment]
[requires.txt](https://github.com/fedora-infra/fedora-packages/files/357130/requires.txt)

**Comment by alx-pl** [comment]
Thank you. I'll report it there then.

**Comment by pypingou** [comment]
Thanks :)
