### ISSUE TITLE
some search always return errors 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fedora-packages#246]
Hi, 
I  remember that I  had this problem some months ago , now I found it again, why https://apps.fedoraproject.org/packages/s/qt5-qttools always return Error loading the data for this page element ?
also https://apps.fedoraproject.org/packages/s/qttools

**Comment by sergiomb2** [comment]
also this search , 
https://apps.fedoraproject.org/packages/s/linguist%2520qt5

search for any qt5- give us one error !

**Comment by sergiomb2** [comment]
just search qt5 and can't go to second page of results ! give error go to 
https://apps.fedoraproject.org/packages/s/qt5 and click in more to see the error !

**Comment by cverna** [comment]
This is fixed in the latest version deployed in production
