### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by strugee** [fedora-infra/fedora-packages#247]
I'm working on a project where I need to periodically check the versions of a package in different Fedora releases, and get notified if they change.

I'd like to just query a JSON API for this. From searching the issues of this repository, it _seems_ like such an API exists, but I can't find any documentation anywhere on how to actually use it.

**Comment by pypingou** [comment]
So there isn't such API for https://apps.fedoraproject.org/packages/ there is https://github.com/fedora-infra/pkgwat.cli which queries this web app but iirc it's actually scrapping the html.

For versions of the packages in the different Fedora release, I would recommend either:

* fedmsg -> real-time notifications: http://fedmsg.com/
* mdapi -> access to the yum's repositories metadata: https://apps.fedoraproject.org/mdapi/
* bodhi -> the gateway through which all packages go before ending to a repository (I'm pretty sure there is an API for it, but I don't have the link to the API's doc handy right now)
