### ISSUE TITLE
Upstream URLs are missing for many projects

### ISSUE THREAD

**Issue by genodeftest** [fedora-infra/fedora-packages#248]
Many projects have missing URLs on apps.fp.o, including but not limited to:
- liferea (see #233): https://apps.fedoraproject.org/packages/liferea
- cherrytree: https://apps.fedoraproject.org/packages/cherrytree
- xdg-desktop-portal: https://apps.fedoraproject.org/packages/xdg-desktop-portal
- flatpak: https://apps.fedoraproject.org/packages/flatpak
- gitg: https://apps.fedoraproject.org/packages/gitg
- meson: https://apps.fedoraproject.org/packages/meson
- ccache: https://apps.fedoraproject.org/packages/ccache

What these packages have in common:
- all packages provide a "URL:" field in their .spec file
- all packages show a URL if queried in `dnf info [packagename]`
  So there is absolutely nothing wrong with these packages, the issue is on the apps.fp.o side.

Some examples for projects which are not affected:
- eclipse
- firefox
- nautilus
- etckeeper, etckeeper-dnf, etckeeper-bzr
- colorgcc

Some correlations I noted:
- All packages with broken URLs don't have patches in their package source git repo available under https://pkgs.fedoraproject.org/cgit/rpms/[packagename].git/tree/. Other files like ccache.sh.in in the ccache package don't seem to influence this behavior.
- Most packages with working URLs on apps.fp.o have patches in their source git repo, even if the patch is not applied (in case of [nautilus](https://pkgs.fedoraproject.org/cgit/rpms/nautilus.git/tree/nautilus.spec) for example). This is not true for all packages, e.g. not for python-hwdata and hwdata.
- subpackages behave the same way as their "parent" package

**Comment by junghans** [comment]
Same for:

- votca-csg: https://apps.fedoraproject.org/packages/votca-csg
- votca-tools: https://apps.fedoraproject.org/packages/votca-tools
- legion: https://apps.fedoraproject.org/packages/legion

**Comment by cverna** [comment]
This should be fix by #326.

**Comment by mjg** [comment]
As one can easily check with the URLs given above, the fix to #326 does not fix the present issue. Or is that one not live yet?

**Comment by cverna** [comment]
This fix was not released yet. I working on trying to get a new release out within the next 1 week or 2.

**Comment by alick** [comment]
Any update?

**Comment by cverna** [comment]
@alick this is now fixed and deployed in production. Let me know if you have faced a problem with it otherwise I ll close this issue

**Comment by genodeftest** [comment]
I can confirm that this bug is fixed in production now. Thank you very much!
