### ISSUE TITLE
small, new problems after F23 -> F24

### ISSUE THREAD

**Issue by rogerkwells** [fedora-infra/fedora-packages#250]
Just a couple of smallish things after upgrading (via dnf) from F23 to
F24 a couple of months ago
deja-dup gui:

1. one has to deselect then reselect the Overview option in order
to be offered the "Backup Now" option.

2. The details option in the progress dialog will only display two
or three lines, is not resizeable, and does not follow resizing the
entire dialog

3. The progress dialog does not wait to be dismissed at the end,
causing any messages about problems (like failure to backup a particular
file) to not be seen

Desktop is: gnome-desktop3-3.20.2-1.fc24.x86_64
laptop is: Thinkpad X240 (Intel graphics)

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
