### ISSUE TITLE
dnf update or dnf install (package) displaying dnf python error code

### ISSUE THREAD

**Issue by MaX121** [fedora-infra/fedora-packages#252]
FYI :: I'm using some copr repos on my Fedora desktop. 

Fedora 24 Workstation

![14542390_1555510094474927_3543654059042544551_o](https://cloud.githubusercontent.com/assets/6882931/19070461/8cbcabf2-8a55-11e6-8968-2b5f40ba1fe5.jpg)

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
