### ISSUE TITLE
[yum] AttributeError: FakeRepository instance has no attribute 'compare_providers_priority'

### ISSUE THREAD

**Issue by drmuey** [fedora-infra/fedora-packages#256]
This is not an issue in yum v3.2.29 but we are seeing it in v3.4.3.

The pseudo package “installed” is a FakeRepository object.

```._compare_providers()``` in v3.4.3 now does:

```
# Respect the repository priority for each provider, the default is 80
            pkgresults[po] += (100 - po.repo.compare_providers_priority) * 10
            self.verbose_logger.log(logginglevels.DEBUG_4,
                _('compare_providers_priority for %s is %s' % (po, po.repo.compare_providers_priority)))
```

the problem being that the FakeRepository class does not have ```compare_providers_priority```.

We worked around this for now by doing this at the top of our library:

```
if not hasattr(yum.packages.FakeRepository, 'compare_providers_priority'):
    yum.packages.FakeRepository.compare_providers_priority = 99
```

**Comment by drmuey** [comment]
I was sent to this github issue tracker from a search for filing a bug report against yum. If this is the wrong spot to do so please let me know, thanks!

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com

**Comment by drmuey** [comment]
thanks!

**Comment by pypingou** [comment]
Sure thing :)

**Comment by drmuey** [comment]
For posterity: https://bugzilla.redhat.com/show_bug.cgi?id=1396248

thanks again :)
