### ISSUE TITLE
SCM link points to old URL

### ISSUE THREAD

**Issue by puiterwijk** [fedora-infra/fedora-packages#259]
The SCM link points to https://pkgs.fp.o/. This should now be https://src.fp.o/

**Comment by puiterwijk** [comment]
Example: SCM on https://apps.fedoraproject.org/packages/zsh points to https://pkgs.fedoraproject.org/cgit/zsh.git

**Comment by QuLogic** [comment]
This is rather annoying since the older one doesn't have a valid cert.

**Comment by pypingou** [comment]
Fixed in #262
