### ISSUE TITLE
accelerating fedora kernel via GPGPU using SkelCl or OpenCl

### ISSUE THREAD

**Issue by tiagmoraismorgado** [fedora-infra/fedora-packages#267]
**Greetings**

It **could be awesome,** if within a sense, **we could:**

- **accelerate Fedora Kernel using GPGPU/HAS**

For that very same purpose I suggest we end up using either **OpenCl framework** or **Muenster university** high level abstraction of **OpenCL** **SkelCl** https://github.com/skelcl/skelcl

**Looking forward to hear from you guys,** cheers
**xx
T.**

**Comment by puiterwijk** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
