### ISSUE TITLE
Help me to complete this Guide about WineHQ !!

### ISSUE THREAD

**Issue by Nokia808** [fedora-infra/fedora-packages#269]
Hi. This is not a bug. It is a need help from you to achieve secure installation of WineHQ. I instructed by WineHQ forum modulator to ask you here about this issue. Please read my post in WineHQ forum:

https://forum.winehq.org/viewtopic.php?f=8&t=28652

As, you see, finally I applied my dream about run WineHQ in supper secure way & risks free. I was, all this time, collecting data & information & searching for a 2nd (or in fact a 3rd) laptop to be used as a lab for trail of this guide (my 2nd old laptop has openSUSE for learning other things).

I discover somethings not suitable for Fedora & correct some commands to be fit for Fedora. Finally it work O.K apart from the following issue (please read post on WineHQ):

Fedora WineHQ packages are custom not official. They involves .desktop files that STILL ENABLE USER ON 1ST USER (OWNER ACCOUNT WHICH HAS SU & SUDO) TO LAUNCH GUI FOR WINE + CERTAIN BUILD IN WINDOWS APPLICATIONS. Click any one of these icons in applications menu will lead to creation .wine

But till now any of these GUI or build in Windows applications NEVER BE POSSIBLE TO RUN FROM TERMINAL & NOT POSSIBLE (TILL THIS MOMENT) TO RUN ANY WINDOWS FILE FROM THEM (I NOT SURE 100% THAT THIS WILL REMAIN FOR EVER, & FOR THAT I OPEN THIS THREAD).

These icons are:

- Notepad
- Regedit
- Wine Boot
- Wine Configuration
- Wine File
- Wine Help
- Wine OLE View
- Wine Software Uninstaller
- Wine Wordpad
- other application appeared under "Game" in application menu.

Any modification of them off course never effect wineuser account.

So, issues about them are:

1) where these are located ?? What I have to type with "which" command to locate them ?? I tried all packages & dependencies installed with wine but all of them changed regarding their ownership & permission where I received error messages corresponding error message I recieved when run "which wine" : not found.

We need to know their location so as to apply on them:
- change ownership of binary 1st, then, change it's right, in following sequence:
sudo chown root:riskywork $(which foo)
sudo chmod 750 $(which foo)

2) does these .desktop files risky, under-mind thins approach or not ?

3) I'm already delete them from application menu on my Cinnamon on my owner user account (which has sudo & su power) by: right click applications menu icon, click "configure ...", & use menu editor to delete all these icons. Is this enough or not ?

 Please your kind help & attention. It is a crime not to complete this guide, because it will be of great usefulness for many users - Using WineHQ without risks !!

**Comment by pypingou** [comment]
Hi,

Thank you for your report, but this project is about the web application running at: https://apps.fedoraproject.org/packages/ so not in any way related to the subject at hand.

I would encourage you to seak help on the fedoraforum or potentially ask.fedoraproject.org, but I doubt you will be able to find this kind of help on github.

Good luck!
