### ISSUE TITLE
Please show "latest stable version" for a package instead of "latest build"

### ISSUE THREAD

**Issue by sanjayankur31** [fedora-infra/fedora-packages#272]
The packages application shows the latest build at the moment. However, this isn't too useful for end users. Would it be possible to show the latest stable versions for the currently supported Fedora releases on the package front page instead? Developers looking for latest builds for whatever reason can click on the builds tab to get information on builds anyway.

The idea here is that an end user could use the application to confirm whether or not she/he is using the latest version of the package.

**Comment by genodeftest** [comment]
Where does it do that? In the overview it shows the latest released version, which is perfect and exactly what you were asking for, right?

**Comment by cverna** [comment]
Yes this was fixed recently so we can close this issue :)

Thanks
