### ISSUE TITLE
mscore 2.1 available. fyi

### ISSUE THREAD

**Issue by dpawson** [fedora-infra/fedora-packages#274]
My system shows

>  dnf info mscore
Last metadata expiration check: 1 day, 0:27:02 ago on Tue May 23 16:01:46 2017.
Installed Packages
Name        : mscore
Arch        : x86_64
Epoch       : 0
Version     : 2.0.3
Release     : 3.fc25

https://musescore.org/en/download  shows 2.1 available.

Dave P

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
