### ISSUE TITLE
Search by packager

### ISSUE THREAD

**Issue by jflory7** [fedora-infra/fedora-packages#278]
# Summary 

Given that [PkgDB is going away](https://fedoraproject.org/wiki/Infrastructure/WhatHappenedToPkgdb) soon, it would be helpful to be able to search by individual packagers (name, email, or FAS account).

# Description

It might help to add a dropdown that lets you filter your search by various criteria. This is a really nice part of PkgDB, so it might help to "export" this type of filtered search into fedora-packages.

![pkgdb-search-menu](https://user-images.githubusercontent.com/4721034/27610651-d9a24ea6-5b54-11e7-98bc-416162d1ee33.png)

**Comment by cverna** [comment]
This is now available in staging and will be deployed in production soon

**Comment by jflory7** [comment]
Super! Didn't know this was being worked on. Thanks for implementing it!
