### ISSUE TITLE
Obsoletes - key "ops" and Less than.

### ISSUE THREAD

**Issue by arielb2** [fedora-infra/fedora-packages#28]
The key "ops" arrive in blank with obsoletes and Less than , but shown on page.

]$ pkgwat -v obsoletes git
initialize_app
prepare_to_run_command Obsoletes
Starting new HTTP connection (1): localhost
"GET /fcomm_connector/yum/query/query_obsoletes/%7B%22rows_per_page%22:%2010,%20%22start_row%22:%200,%20%22filters%22:%20%7B%22repo%22:%20%22Rawhide%22,%20%22version%22:%20%221.8.3.1-1.fc20%22,%20%22arch%22:%20%22x86_64%22,%20%22package%22:%20%22git%22%7D%7D HTTP/1.1" 200 251
+----------------------------+
| Obsoletes                  |
+----------------------------+
| git-core < = 0-1.5.4.3     |
| git-arch  0-1.8.3.1-1.fc20 | *******not have the <
+----------------------------+

![obsoletes](https://f.cloud.github.com/assets/3988316/771310/a170afea-e8e0-11e2-85cc-49c60e29334d.png)

Received:

[{u'provided_by': None, u'version': u'0-1.5.4.3', u'flags': u'LE', u'name': u'git-core', u'ops': u'< ='}, {u'provided_by': None, u'version': u'0-1.8.3.1-1.fc20', u'flags': u'LT', u'name': u'git-arch', u'ops': ''}]

also spaces
u'ops': u'< ='

**Comment by ralphbean** [comment]
Well, the obsoletes/relationships code has been removed now, so I'm going to close this one as wontfix.
