### ISSUE TITLE
SCM links should use "Pagure over dist-git" instead of cgit

### ISSUE THREAD

**Issue by mprahl** [fedora-infra/fedora-packages#282]
Currently the "SCM" links point to cgit instead of Pagure over dist-git.

For instance, [bpython](https://apps.fedoraproject.org/packages/bpython) has an SCM link of https://pkgs.fedoraproject.org/cgit/bpython.git when it should now be https://src.fedoraproject.org/rpms/bpython.

**Comment by techtonik** [comment]
The same problem with etckeeper, which eventually points to broken https://src.fedoraproject.org/etckeeper.git

**Comment by cverna** [comment]
Fixed by #283

**Comment by ctubbsii** [comment]
This is marked closed, but it doesn't actually seem to have been fixed yet.

**Comment by pypingou** [comment]
We close when it's fixed in git, not when it's deployed. Not ideal we realize but that's the current workflow.

**Comment by ctubbsii** [comment]
Got it. It kinda seems like maybe there should be a separate issue tracker for the backend and the user-facing site itself, with the backend "upstream" of the site, but maybe that's overkill if the site is deployed regularly.

When do you expect this fix will be deployed to the site?

**Comment by pypingou** [comment]
@cverna is actively working on deploying a new release. I know they had some issues with the pre-prod instance yesterday but it's being worked on, so... soonish? :)

**Comment by richardfearn** [comment]
See also https://pagure.io/fedora-infrastructure/issue/6206
