### ISSUE TITLE
packages page doesn't get create for new packages 

### ISSUE THREAD

**Issue by junghans** [fedora-infra/fedora-packages#288]
After pushing new packages to rawhide, https://apps.fedoraproject.org/packages/PKG should be create, but e.g. for lammps that isn't the case: https://apps.fedoraproject.org/packages/lammps.

**Comment by ralphbean** [comment]
Should be fixed by #281.

**Comment by cverna** [comment]
The #281 work was merged as part of #290. So I am closing this.

Thanks for the report

**Comment by junghans** [comment]
Still no https://apps.fedoraproject.org/packages/lammps?
