### ISSUE TITLE
Usage of pkgdb should be replaced

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fedora-packages#289]
packages uses pkgdb for a number of things currently, and since we are no longer using pkgdb we should switch these use cases over to pdc or pagure over dist git or whatever makes sense. 

Downstream report: 
https://pagure.io/fedora-infrastructure/issue/6336

**Comment by pypingou** [comment]
This is WIP in #280 and #281

**Comment by techtonik** [comment]
Or in #290?

**Comment by Grinnz** [comment]
Is this still in progress? The linked PRs seem to be completed.

**Comment by pypingou** [comment]
I'll let @cverna reply but I believe this can be closed indeed :)

**Comment by cverna** [comment]
Let's close it 👍
