### ISSUE TITLE
A number of links to the retired fedorahosted.org should be updated

### ISSUE THREAD

**Issue by zploskey** [fedora-infra/fedora-packages#291]
For example, the README starts with this link:

https://fedorahosted.org/fedoracommunity/wiki/Development

It currently leads to a page about the retirement of fedorahosted.org.

Should this instead be https://fedoraproject.org/wiki/Fedora_Community ? I'm not sure exactly what was on the fedoracommunity wiki page and if it's the same one. Has it been moved somewhere else?

There are of course other links that need to be updated, including the "Get the source for Moksha" links on the bottom of every page.

There are a few others:
- The URL in the package spec: https://github.com/fedora-infra/fedora-packages/blob/8f7b75dc21c1e1a1d4ce5a81f03476045c99e05c/fedora-packages.spec#L12
- This link to a ticket: https://github.com/fedora-infra/fedora-packages/blob/4d549df0a06ca48c2208d1b55c8f1e96631beeed/fedoracommunity/connectors/bugzillaconnector.py#L254

There are also some links that are wrong in files under fedoracommunity/public/pages/tour but I have not found a way yet to access them in the application.

This should give all the links:
https://github.com/fedora-infra/fedora-packages/search?q="fedorahosted.org"

**Comment by techtonik** [comment]
Repository description doesn't match contents too:

> A webapp that visualizes data from various pieces of Fedora Infrastructure. Written in Python using TurboGears2 and Moksha.

**Comment by zploskey** [comment]
@techtonik How so? Anyways, that is unrelated to this issue. If you think there is something else to be addressed perhaps you should make a separate issue.

**Comment by techtonik** [comment]
@zploskey repository description is fixed.

**Comment by cverna** [comment]
@zploskey and @techtonik I have updated the description and also submitted #302 to fix the readme.

**Comment by toanju** [comment]
not sure if this should go into a separate issue, but all links pointing to the scm are broken, e.g.:

kernel (meta) package at
https://apps.fedoraproject.org/packages/kernel

is pointing to
https://src.fedoraproject.org/cgit/kernel.git

though the actual location is:
https://src.fedoraproject.org/cgit/rpms/kernel.git

**Comment by pypingou** [comment]
This has also been fixed :)
