### ISSUE TITLE
Error loading the data for this page element

### ISSUE THREAD

**Issue by RobberPhex** [fedora-infra/fedora-packages#293]
When I view <https://apps.fedoraproject.org/packages/gnome-shell/overview>,

I have this error:

![f767ee9b-aeda-4157-bc32-8d954e944c28](https://user-images.githubusercontent.com/1926185/30677374-0531c5c2-9ebe-11e7-820a-3fb540c71ccf.png)

The request `https://apps.fedoraproject.org/packages/fcomm_connector/bodhi/query/query_active_releases/%7B%22filters%22:%7B%22package%22:%22gnome-shell%22%7D,%22rows_per_page%22:10,%22start_row%22:0%7D` is 500,

The `https://apps.fedoraproject.org/datagrepper/raw?order=desc&meta=subtitle&meta=link&meta=icon&meta=secondary_icon&package=gnome-shell&grouped=true&not_topic=org.fedoraproject.prod.buildsys.rpm.sign&not_topic=org.fedoraproject.prod.buildsys.tag&not_topic=org.fedoraproject.prod.buildsys.untag&not_topic=org.fedoraproject.prod.buildsys.package.list.change&rows_per_page=20&callback=jQuery171047953307127719347_1505963449594&_=1505963451645` is 503.

**Comment by petersaints** [comment]
This happens on any package that I search for on https://apps.fedoraproject.org/packages/. Please fix it.

**Comment by cverna** [comment]
This was fixed by https://pagure.io/fedora-infrastructure/issue/6401.
