### ISSUE TITLE
 SCM link it outdated!

### ISSUE THREAD

**Issue by RobberPhex** [fedora-infra/fedora-packages#294]
the scm link at <https://apps.fedoraproject.org/packages/gnome-shell/overview> is link to <https://pkgs.fedoraproject.org/cgit/gnome-shell.git>, which has ssl cert error:

![41505963809_ pic_hd](https://user-images.githubusercontent.com/1926185/30677469-6c59157a-9ebe-11e7-9ce6-b569c465020a.jpg)

**The SCM link should be <https://src.fedoraproject.org/cgit/rpms/gnome-shell.git>**

**Comment by ralphbean** [comment]
I *think* this is a duplicates of #282 and #285.

**Comment by RobberPhex** [comment]
I *think* we can close this issue when the SCM link at <https://apps.fedoraproject.org/packages/gnome-shell/overview> is updated.

**Comment by pypingou** [comment]
It is a duplicate, so let's close :)
