### ISSUE TITLE
Centos 7.4

### ISSUE THREAD

**Issue by eccare** [fedora-infra/fedora-packages#298]
I was not able to wade through the epel links to request that they include orthanc in their repositories.  After trying several times to login to their system I was not able to do so.

I would surely be appreciate if the orthanc package became part of the Centos 7 epel packages.

**Comment by puiterwijk** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com.

**Comment by eccare** [comment]
Ok, thanks much
