### ISSUE TITLE
Unable to find builds for 'perl'

### ISSUE THREAD

**Issue by Grinnz** [fedora-infra/fedora-packages#306]
If you search for 'perl' on the packages app now, you get https://apps.fedoraproject.org/packages/perl/ which shows perl as a 'subpackage of perl-bignum', this is clearly incorrect. The description and changelog appear to be for the 'perl' package but everything else is describing 'perl-bignum'.

**Comment by cverna** [comment]
This was fixed in the latest release which now deployed in production.
