### ISSUE TITLE
"SCM" link still links to old pkgs.fedoraproject.org cgit interface

### ISSUE THREAD

**Issue by richardfearn** [fedora-infra/fedora-packages#310]
e.g. for `rlwrap` URL is https://pkgs.fedoraproject.org/cgit/rlwrap.git but should be https://src.fedoraproject.org/rpms/rlwrap.

**Comment by pypingou** [comment]
This is a duplicate of #294

**Comment by richardfearn** [comment]
Thanks - I didn't include closed tickets in my search :-/
