### ISSUE TITLE
No info under packages link for python-enlighten

### ISSUE THREAD

**Issue by avylove** [fedora-infra/fedora-packages#311]
When following the [Packages](https://apps.fedoraproject.org/packages/s/python-enlighten) link in [Pagure](https://src.fedoraproject.org/rpms/python-enlighten), there is no package information for [python-enlighten](https://apps.fedoraproject.org/packages/s/python-enlighten) like I see for other packages. Perhaps some data is missing?

**Comment by cverna** [comment]
Hi @avylove, thanks for the report. We already have a ticket for this #286, so I will close your ticket as duplicate.

#286 has been solved and we are working on deploying the new version of the application in production.
