### ISSUE TITLE
apps.fp.o/packages seems out of date with actual package collection

### ISSUE THREAD

**Issue by Conan-Kudo** [fedora-infra/fedora-packages#319]
It seems that the package collection is out of date relative to what's in the repositories.

For example, [mir](https://koji.fedoraproject.org/koji/packageinfo?packageID=25835) doesn't show up there.

It seems new packages aren't getting tracked by package search system.

**Comment by cverna** [comment]
@Conan-Kudo A new version of packages is currently being deployed, it will resolve this issue.

**Comment by avsej** [comment]
@cverna is it still deploying?

**Comment by pypingou** [comment]
yes, we're still working on it :)

**Comment by cverna** [comment]
@avsej and @Conan-Kudo the new version has been deployed. 

mir is now available, so closing this ticket
