### ISSUE TITLE
The same design as Pagure is bad

### ISSUE THREAD

**Issue by techtonik** [fedora-infra/fedora-packages#322]
[New version was deployed today.](https://github.com/fedora-infra/fedora-packages/issues/299#issuecomment-353658000) And I want to bring this issue under my first impression.

Design for app that is almost the same as app for another part of infrastructure is very confusing. Launchpad did this mistake - mixed design of its package management system with issue tracker + VCS. It might not be bad to have everything at one place, but without clear distinction it was hard to understand why something is a package and something is a project and what is the difference - where you should report you issues.

There should be at least different background, because what happens in Pagure is impossible in packages app and vice versa. People like me will try to find something they've seen in other interface and will get frustrated if it is not there. This user experience can be improved with design change.

**Comment by techtonik** [comment]
One of the enhancements could be to add project logo in a box.

https://apps.fedoraproject.org/packages/keepass/

**Comment by cverna** [comment]
I am closing this issue but if you wish to submit a PR to update the styling I ll be happy to review it.

**Comment by techtonik** [comment]
@cverna can we at least come to a consensus that a design change is needed?

**Comment by techtonik** [comment]
https://apps.fedoraproject.org/packages/bodhi

![image](https://user-images.githubusercontent.com/515889/48132859-faccb100-e2a5-11e8-92d8-cc9a05d5394d.png)
https://pagure.io/bodhi

![image](https://user-images.githubusercontent.com/515889/48132960-38313e80-e2a6-11e8-89d3-d8fab78db8a7.png)

Ok. Now it is more or less different.

**Comment by techtonik** [comment]
No. Icon should have a different shade of gray.

**Comment by techtonik** [comment]
Here we go - https://github.com/fedora-infra/fedora-packages/pull/407
