### ISSUE TITLE
Description of package chromium seems wrong

### ISSUE THREAD

**Issue by heis2201** [fedora-infra/fedora-packages#324]
Looking at the package information for `chromium` [here](https://apps.fedoraproject.org/packages/chromium), it seems as if the description (see below) is not correct. It reads like the description for the `chrome-remote-desktop` package instead.

Description for `chromium`: *Remote desktop support for google-chrome & chromium*

**Comment by cverna** [comment]
This is now fixed in mdapi see (https://pagure.io/mdapi/pull-request/68#)
