### ISSUE TITLE
Data is not updated

### ISSUE THREAD

**Issue by voxik** [fedora-infra/fedora-packages#332]
libxcrypt \[[1]\] is in Fedora already for some while, but packages does not know anything about it \[[2]\]. It seems the data are not properly updated.

[1]: https://src.fedoraproject.org/rpms/libxcrypt
[2]: https://apps.fedoraproject.org/packages/s/libxcrypt

**Comment by voxik** [comment]
Actually I get this \[[1]\] link from pagure \[[2]\]which redirects me to the search ....


[1]: https://apps.fedoraproject.org/packages/libxcrypt/bugs
[2]: https://src.fedoraproject.org/rpms/libxcrypt

**Comment by cverna** [comment]
The fedmsg consumer that is supposed to update the database with new packages is throwing exceptions. 

The consumer code needs to be changed to match the changes done in #301

**Comment by cverna** [comment]
Fixed by #338

**Comment by voxik** [comment]
Thx. Is there a chance to get the data updated? I don't think fixing the fedmsg consumer will update them at this stage.

**Comment by cverna** [comment]
When we will deploy a new version of packages, it will rebuild the database using the latest data. From then the fedmsg consumer will keep the data up to date.
