### ISSUE TITLE
Descriptions come from a random subpackage

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/fedora-packages#333]
For example, looking at the [gcc](https://apps.fedoraproject.org/packages/gcc) page, the description appears to come from the cpp subpackage. Also happens with [gcc-gdb-plugin](https://apps.fedoraproject.org/packages/gcc-gdb-plugin), [gcc-go](https://apps.fedoraproject.org/packages/gcc-go), [gcc-offload-nvptx](https://apps.fedoraproject.org/packages/gcc-offload-nvptx), [libgcc](https://apps.fedoraproject.org/packages/libgcc), [libgo-static](https://apps.fedoraproject.org/packages/libgo-static), [libgomp](https://apps.fedoraproject.org/packages/libgomp), and [liblsan](https://apps.fedoraproject.org/packages/liblsan), but not the other subpackages. I don't really know what differentiates the two sets.

**Comment by QuLogic** [comment]
The summary and description of [`qhull` is even worse](https://apps.fedoraproject.org/packages/qhull) as it's just `-n libqhull`.

**Comment by cverna** [comment]
Relates to #324

**Comment by cverna** [comment]
This is fixed in mdapi (https://pagure.io/mdapi/pull-request/68#)
