### ISSUE TITLE
Number of bugs links filters on product=Fedora

### ISSUE THREAD

**Issue by cverna** [fedora-infra/fedora-packages#350]
Bug originally  reported here https://pagure.io/fedora-infrastructure/issue/6714

When clicking on the number of bugs link we redirect to bugzilla url with the following parameter `&product=Fedora`. This is not correct since this does not include other products like Fedora EPEL.

**Comment by cverna** [comment]
We are setting `Fedora` as product here https://github.com/fedora-infra/fedora-packages/blob/develop/fedoracommunity/widgets/package/bugs.py#L13

**Comment by the1derer** [comment]
So, should I just change the value of product to "&product=Fedora+FedoraEPEL" ?

**Comment by cverna** [comment]
@the1derer yes this is the idea, you need to look [here](https://github.com/fedora-infra/fedora-packages/blob/develop/fedoracommunity/widgets/package/bugs.py#L13) and see how to add a second product.

**Comment by arshadkazmi42** [comment]
is this bug still open? I am looking for some easyfix to get started with the contribution.

**Comment by cverna** [comment]
@arshadkazmi42 yes this bug is still open, you can work on it :)

**Comment by abitrolly** [comment]
We are experiencing temporary technical debt. Stay tuned. :D

For troubleshooting it is possible to run `docker-compose exec web bash`.  For `DistributionNotFound` it is better to see log of `docker-compose build`. CI is not setup for this repository, and there is not log to look at right away.

**Comment by abitrolly** [comment]
https://github.com/fedora-infra/fedora-packages/pull/395#issuecomment-412376849

**Comment by steaksauce-** [comment]
I've begun to take a look at this. I found the line in question, [here](https://github.com/fedora-infra/fedora-packages/blob/master/fedoracommunity/widgets/package/bugs.py#L13), but I'm afraid I'm not sure on what to add to the class to add multiple items.

To be clear, I know that the syntax added to the web URL will be product=Fedora&product=FedoraEPEL.

With that end result in mind, I'm not sure what the class would look like in the aforementioned file. Any pointers for a newbie?

**Comment by cverna** [comment]
@steaksauce- I would start looking at the http://toscawidgets.org/documentation/tw2.core/ documentation and see if it is possible to have 2 values for the same parameter.

**Comment by steaksauce-** [comment]
Thanks, @cverna 

I took a look and I don't think that it supports a second parameter. I was going to try a hacky way of going about this: `product = twc.Param(default='Fedora&product=FedoraEPEL')`

However, I'm having trouble with my dev environment (docker runs, but can't find the packages directory in the site. Vagrant starts, but the web page has "{{html name}} | {{html summary}}-- | -- {{html pkg["name"]}} | {{html pkg["summary"]}}" in it, so I don't think something is running right).

I'm on a KDE Neon box right now. I'll try the dev environment on my Fedora box when I get the chance.

**Comment by steaksauce-** [comment]
I see two ways around this (I have my ideal way, but I can't quite figure out the syntax):

Way 1: For other items that have multiple values (such as the status field), the url string is hardcorded: `status_open_string = "bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED"`
We could do the same thing for the products.

Way 2 (ideal): Because `urllib.encode` will not let us assign two different key/value pairs with the same key name, we get it to recognize an array for the product values. If there is a way to make this work, we can clean up the code for the bug status as well.

I've tried a few different methods over the past hour and can't get this working. If I have `product1 = twc.Param(default='Fedora')` and `product2 = twc.Param(default='FedoraEPEL')` and try to make `product` an array within `urllib.encode`, I get different results ranging from server 500 errors, syntax errors, and other undesirable results.

I even tried to make `product = [twc.Param(default='Fedora'), twc.Param(default='FedoraEPEL')]`, but I get something like:
```
product=[None%3A None (default%3A Fedora%2C defined on%3A None)%2C None%3A None (default%3A FedoraEPEL%2C defined on%3A None)]&query_format=advanced
```

**Comment by cverna** [comment]
> I see two ways around this (I have my ideal way, but I can't quite figure out the syntax):
> 
> Way 1: For other items that have multiple values (such as the status field), the url string is hardcorded: `status_open_string = "bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED"`
> We could do the same thing for the products.
> 
> Way 2 (ideal): Because `urllib.encode` will not let us assign two different key/value pairs with the same key name, we get it to recognize an array for the product values. If there is a way to make this work, we can clean up the code for the bug status as well.
> 
> I've tried a few different methods over the past hour and can't get this working. If I have `product1 = twc.Param(default='Fedora')` and `product2 = twc.Param(default='FedoraEPEL')` and try to make `product` an array within `urllib.encode`, I get different results ranging from server 500 errors, syntax errors, and other undesirable results.
> 
> I even tried to make `product = [twc.Param(default='Fedora'), twc.Param(default='FedoraEPEL')]`, but I get something like:
> 
> ```
> product=[None%3A None (default%3A Fedora%2C defined on%3A None)%2C None%3A None (default%3A FedoraEPEL%2C defined on%3A None)]&query_format=advanced
> ```

@steaksauce- Thanks for looking at this :+1: , I think that the first solution is fine, I am not sure this is worth the effort of trying to get the second way working. But the choice is up to you :smiley:

**Comment by steaksauce-** [comment]
I've got some desirable results playing around in the Python shell, I just need to get it into the code. Hockey season is slowing me down, but I should hopefully have a pr this weekend or next week.

**Comment by steaksauce-** [comment]
#404 works in my test environment :1st_place_medal:
