### ISSUE TITLE
Incorrect meta show on utop package

### ISSUE THREAD

**Issue by avsej** [fedora-infra/fedora-packages#351]
Instead of `utop` package, this page shows information about `python-autopep8`
https://apps.fedoraproject.org/packages/utop/overview/

![image](https://user-images.githubusercontent.com/7280/37571576-7910930a-2b0f-11e8-8187-be18b315b6e8.png)

**Comment by cverna** [comment]
I am not sure what happened here, I need to investigate the indexing of the search database.

**Comment by cverna** [comment]
This is fixed now
