### ISSUE TITLE
Bug dropdown does not work in some cases

### ISSUE THREAD

**Issue by rugk** [fedora-infra/fedora-packages#353]
STR:
1. Go to https://apps.fedoraproject.org/packages/android-tools/bugs/. Dropdown works.
2. Switch to another tab and fastly switch back to "Bugs".

What happens: Dropdown does not work anymore.

What should happen: Dropdown should always work.

Firefox 59

**Comment by lentzi90** [comment]
Also affects Chrome

**Comment by lentzi90** [comment]
This seems to be a duplicate of #349
