### ISSUE TITLE
All subpackages are broken

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/fedora-packages#360]
For example, [gcc](https://apps.fedoraproject.org/packages/gcc) shows a bunch of subpackages, but if you click on any of them (e.g., [gcc-gnat](https://apps.fedoraproject.org/packages/gcc-gnat), [libgccjit](https://apps.fedoraproject.org/packages/libgccjit), [libmpx](https://apps.fedoraproject.org/packages/libmpx), etc.), you find a page with no versions and no link back to the main package.

**Comment by QuLogic** [comment]
Ping? This is really quite annoying.

**Comment by cverna** [comment]
Hi thanks for the report. I ll look at it today

**Comment by QuLogic** [comment]
Any updates?

**Comment by QuLogic** [comment]
Another related thing: [python3-mplcursors](https://apps.fedoraproject.org/packages/python3-mplcursors) and [python-mplcursors-doc](https://apps.fedoraproject.org/packages/python-mplcursors-doc) are subpackages of [python-mplcursors,](https://apps.fedoraproject.org/packages/python-mplcursors) but the first two show up as empty, and the latter cannot be found.

**Comment by cverna** [comment]
I ll try to rebuild the xapian database today see if that fixes some of these errors

**Comment by cverna** [comment]
I just rebuild the index database, but mdapi does not know about f29 which makes all results with `no description in mdapi` ... 

Once we fix mdapi I ll rebuild the index again

See infra ticket for mdapi https://pagure.io/fedora-infrastructure/issue/7291

**Comment by cverna** [comment]
This is finally fixed :fireworks:

**Comment by genodeftest** [comment]
Wow, nice! Thank you very much! This makes using apps.fp.o sooooo much easier…
