### ISSUE TITLE
Right Click drop down not working in my fedora 28

### ISSUE THREAD

**Issue by jatin-cbs** [fedora-infra/fedora-packages#363]
Right Click is not working on my fedora 28 for example when i want to right click and open the link in a new tab, the right click is not working. I have tested on multiple systems same problem. Its working fine with other distros. Fix if that is a problem . Thanks

**Comment by puiterwijk** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be opened on https://bugzilla.redhat.com

**Comment by jatin-cbs** [comment]
ok thanks
