### ISSUE TITLE
Missing space in Recent History

### ISSUE THREAD

**Issue by jamesjer** [fedora-infra/fedora-packages#368]
The recent history shows items such as this (package gmp-ecm):

12 hours agojjames pushed to gmp-ecm (master). "Use %ldconfig_scriptlets."

Notice that there is no space between "ago" and "jjames".

**Comment by pypingou** [comment]
I believe this is a duplicate of https://github.com/fedora-infra/fedora-packages/issues/366 that has been fixed in https://github.com/fedora-infra/fedora-packages/commit/24318774fdcfce9a2b353f6c572f153107017597

Thanks for your report though.
