### ISSUE TITLE
The update system has the wrong package

### ISSUE THREAD

**Issue by stevedd** [fedora-infra/fedora-packages#369]
'm trying to update the rpcsvc-proto package.

When I try to create a new update, the system
only gives me rpcsvc-proto-devel as a choice
not rpcsvc-proto.

This is clearly a bug since rpcsvc-proto-devel
is part of rpcsvc-proto

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
