### ISSUE TITLE
Add "Problems" tab in packages page

### ISSUE THREAD

**Issue by mhabrnal** [fedora-infra/fedora-packages#370]
We would like to add `Problems` tab to packages page. A content of the tab would contain problems obtained from FAF server [1] related to a selected package.
I would add the tab next to `Bugs` tab:
![fedora-problems](https://user-images.githubusercontent.com/8615428/41026152-15a0c904-6974-11e8-8e26-d35b6184f9fc.png)

Are you interested in this? Can I start work on it?
[1] https://retrace.fedoraproject.org/faf

**Comment by cverna** [comment]
@mhabrnal thanks for the feature proposal, but to be honest I would like not to had any new tabs to packages.
The code base is quite old making the application quite difficult to maintain, however it could be an idea to add a link to FAF in the drop down menu (ie abrt in other apps), this would be a trivial change.

What do you think about that ?

**Comment by mhabrnal** [comment]
@cverna a link to FAF is already placed in the drop-down menu.

We know the application is stable and you don't want to add new features to it but it would be fine to have this feature next to bugzilla bugs.

This should be trivial change too, just ask FAF server to get JSON with problems and display them in a table. FAF API is already prepared for this kind of request:

```
$ curl -H "Accept: application/json" https://retrace.fedoraproject.org/faf/problems/?component_names=abrt
```

Of course, I will open a pull request and I am prepared for your strict review :)

**Comment by cverna** [comment]
@mhabrnal what kind of information would be shown in the "Problems"  tab ?

**Comment by mhabrnal** [comment]
@cverna  we are about to add only four columns from [1] (problem ID, state, crash function, and count). All problems would be sorted by count of occurrences. Does it make sense to you?

[1] https://retrace.fedoraproject.org/faf/problems/?component_names=abrt

**Comment by cverna** [comment]
@mhabrnal please go ahead with a PR, but I can't guarantee when this will be reviewed and release.
