### ISSUE TITLE
Email addresses shouldn't be revealed in packages' Recent History

### ISSUE THREAD

**Issue by ozeszty** [fedora-infra/fedora-packages#372]
Bugzilla requires user to be logged-in to see other users' email addresses, yet Fedora Packages shows those emails to everyone (to crawl and start spamming). It should show username rather than email address.

**Comment by pypingou** [comment]
It is potentially a Fedora-Infra issue https://pagure.io/fedora-infrastructure/ but you may want to read https://pagure.io/fedora-infrastructure/issue/5381 as I believe it is the same underlying question.

**Comment by cverna** [comment]
Closing this
