### ISSUE TITLE
Why devel version of xapian?

### ISSUE THREAD

**Issue by abitrolly** [fedora-infra/fedora-packages#375]
Why README recommends to use devel Xapian? Maybe it is already released with needed fixes?
```
$ curl -o devel/docker/xapian.tar.gz https://cverna.fedorapeople.org/xapian.tar.gz 
```

**Comment by abitrolly** [comment]
And it doesn work.
```
$ wget https://cverna.fedorapeople.org/xapian.tar.gz
--2018-07-10 03:59:07--  https://cverna.fedorapeople.org/xapian.tar.gz
Resolving cverna.fedorapeople.org (cverna.fedorapeople.org)... 152.19.134.199, 2610:28:3090:3001:5054:ff:fea7:9474
Connecting to cverna.fedorapeople.org (cverna.fedorapeople.org)|152.19.134.199|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-10 03:59:09 ERROR 404: Not Found.
```
What CI/CD servers Fedora uses?

**Comment by cverna** [comment]
> Why README recommends to use devel Xapian? Maybe it is already released with needed fixes?

This is not the devel version of Xapian this is an archive of the production xapian database with all packages already indexed. This is useful in the development environment so you don't need to rebuild the index which takes hours.

**Comment by abitrolly** [comment]
https://cverna.fedorapeople.org/xapian.tar.gz is 404

**Comment by cverna** [comment]
> And it doesn work.

I ll upload a new version of it

> What CI/CD servers Fedora uses?

I am not sure what you mean here, but for this for project we do not have CI since we have very little unit tests. And the deployment is done via ansible [here](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/playbooks/groups/packages.yml)

**Comment by abitrolly** [comment]
Thanks. Even without unit test it is still useful to have CI to prevent issues with broken development environment, like in #376. These often arise when there are multiple pathways to bootstrap a project (vagrant, docker-compose, ansible).
