### ISSUE TITLE
Packages bear, bear-devel, bear-factory and erlang-bear got mixed together

### ISSUE THREAD

**Issue by D4N** [fedora-infra/fedora-packages#408]
Forward of a report from the devel mailing list:

I have discovered a very weird problem with the package bear on apps.fedoraproject.org: https://apps.fedoraproject.org/packages/bear
It got somehow mixed with the (completely unrelated) packages erlang-bear, bear-devel and bear-factory.

A little bit of background:
- bear is a new package (for which I am the maintainer)
- previously the name was taken by a game engine, which its maintainer kindly renamed to bear-factory
- bear-devel are afaik the development files of the game engine before it got renamed to bear-factory
- erlang-bear has nothing to do with the other packages, beside sharing a part of the name

A few days ago I requested bear to be unorphaned and assigned to me, which has happened. I have imported the sources successfully and triggered a build on rawhide.
However, the system registered that as a build of erlang-bear (but called it just "bear"), which means that I probably just broke the updates of erlang-bear on Rawhide.

I was advised to create an issue here.

**Comment by cverna** [comment]
I think this now fixed, can you confirm ?

**Comment by D4N** [comment]
Not really, bear is still shown as an erlang package, while it actually should be a tool for clang-tooling. Also, the page notes the wrong maintainer.

**Comment by D4N** [comment]
I just checked and the issue is now fixed. Thanks for that!
