### ISSUE TITLE
Eclipse tutorial does not run due to javax.annotation-api being used instead of javax.annotation

### ISSUE THREAD

**Issue by z0rgy** [fedora-infra/fedora-packages#413]
Using the Eclipse through the dnf channel is not working as expected:

I am attempting to build a simple hello world application by creating a new eclipse plugin project and selecting the template of "View contribution using 4.x API".

Building and running that example as it is with no modification does not work as I am getting the following error message:

!MESSAGE Possbible annotation mismatch: method "public void hello.parts.SampleView.createPartControl(org.eclipse.swt.widgets.Composite)" annotated with "javax.annotation-api:1.2.0:javax.annotation.PostConstruct" but was looking for "javax.annotation.PostConstruct [via bootstrap classloader]"

Looking at the jar files within the eclipse /usr/lib/eclipse/plugins I noticed that there are jar files pointing to glassfish:

/usr/lib/eclipse/plugins/javax.annotation-api_1.2.0.jar -> /usr/share/java/glassfish-annotation-api.jar
/usr/lib/eclipse/plugins/javax.el-api_3.0.0.jar -> /usr/share/java/glassfish-el-api.jar
/usr/lib/eclipse/plugins/javax.inject_1.0.0.v20091030.jar -> /usr/share/java/atinject.jar
/usr/lib/eclipse/plugins/javax.servlet-api_3.1.0.jar -> /usr/share/java/glassfish-servlet-api.jar
/usr/lib/eclipse/plugins/javax.servlet.jsp_2.3.2.b01.jar -> /usr/share/java/glassfish-jsp-api/javax.servlet.jsp-api.jar

specifically the javax.annotation-api_1.2.0.jar is different from the other Eclipse downloaded from https://www.eclipse.org/downloads/packages

It comes as javax.annotation_1.2.0.v201602091430.jar which is different.

**Comment by cverna** [comment]
Thanks for your report but this is however, the wrong place for such bug reports.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be opened on https://bugzilla.redhat.com
