### ISSUE TITLE
Conflicts with xdg-utils when installing flatpak-xdg-utils

### ISSUE THREAD

**Issue by kiview** [fedora-infra/fedora-packages#419]
I'm getting the following transaction check error when installing `flatpak-xdg-utils-1.0.0-2.fc30.x86_64.rpm`:

```
Error: Transaction check error:
  file /usr/bin/xdg-email from install of flatpak-xdg-utils-1.0.0-2.fc30.x86_64 conflicts with file from package xdg-utils-1.1.3-4.fc30.noarch
  file /usr/bin/xdg-open from install of flatpak-xdg-utils-1.0.0-2.fc30.x86_64 conflicts with file from package xdg-utils-1.1.3-4.fc30.noarch
```

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com

**Comment by kiview** [comment]
Sorry, thanks for the hint.
