### ISSUE TITLE
button file a new bug doesn't work when we click on tab bugs 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/fedora-packages#425]
for example: 
https://apps.fedoraproject.org/packages/po-debconf/bugs/

**Comment by sergiomb2** [comment]
For some reason it is fixed now , Thanks

**Comment by sergiomb2** [comment]
Hi,
I search and click on a package, for example python3 [1]  and click on tab bugs and button "file a new bug" won't work . But if I navigate directly to [2] it works . I tested in Firefox and in Chrome in both browsers have the same behavior .

[1] https://apps.fedoraproject.org/packages/python3/
[2] https://apps.fedoraproject.org/packages/python3/bugs/

**Comment by jamesjer** [comment]
This is a duplicate of issue 349.

**Comment by rugk** [comment]
Can't you close this as a dupe of #349, @sergiomb2?

**Comment by sergiomb2** [comment]
closing as dupe
