### ISSUE TITLE
ocsinventory-agent 2.6.0.3 is broken after update from Epel repo

### ISSUE THREAD

**Issue by pchamo** [fedora-infra/fedora-packages#428]
### General informations
Operating system :  CentOS Linux release 7.6.1810 & CentOS 7.7.1908
Perl version : v5.16.3

### OCS Inventory informations
Unix agent version : 2.6.0.3

### Problem's description
After update from ocsinventory-agent-2.6.0-2.1 to version ocsinventory-agent-2.6.0-3 from Epel repo the agent stopped working.

```
[root@host ~]# ocsinventory-agent
Failed to load Ocsinventory::Agent, Global symbol "$self" requires explicit package name at /usr/share/perl5/vendor_perl/Ocsinventory/Agent.pm line 166.
Compilation failed in require at (eval 1) line 1.
BEGIN failed--compilation aborted at (eval 1) line 1.

you can run the agent directly for its source directory with --devlib
```

**Comment by pypingou** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
