### ISSUE TITLE
Latexmk pdf incompatible with PDF Mod

### ISSUE THREAD

**Issue by ecjbosu** [fedora-infra/fedora-packages#430]
I use latexmk to create many pdf files at a time from latex files.  Some time I need to join pdfs and PDF Mod is used.  But a pdf create with latexmk generate a generic error with PDF Mod.  If I open the pdf file with Okular or other pdf viewer, choose print to pdf to create a new pdf of the problem pdf, then PDF mod opens the new pdf fine.  The attached file will generate and error with PDF Mod.

[Syllabus.pdf](https://github.com/fedora-infra/fedora-packages/files/4049659/Syllabus.pdf)

Open is pdf viewer of choice, select print to file, and generate a new pdf.  This will open with PDF Mod.

Thanks

**Comment by cverna** [comment]
Thanks for your report but this is however, the wrong place for such bug report.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be open in https://bugzilla.redhat.com
