### ISSUE TITLE
 Cannot search for packages: Error loading the data for this page element

### ISSUE THREAD

**Issue by averyfreeman** [fedora-infra/fedora-packages#433]
Cannot search for packages - result:

"Error loading the data for this page element"

![image](https://user-images.githubusercontent.com/1308847/73421365-787d4200-42da-11ea-95e4-faf119220986.png)

**Comment by cverna** [comment]
Thanks for the report this is a fallback from #432, working on fixing it.

**Comment by averyfreeman** [comment]
Thank you :)  Have a nice day.
