### ISSUE TITLE
packages missing from search

### ISSUE THREAD

**Issue by alex-tee** [fedora-infra/fedora-packages#437]
hi,
the package guile22 cannot be found online https://src.fedoraproject.org/rpms/guile https://apps.fedoraproject.org/packages/s/guile however it shows up when you search through dnf.

**Comment by genodeftest** [comment]
It also affects other packages, e.g. `quiterss`.

**Comment by genodeftest** [comment]
Duplicate of #432

**Comment by cverna** [comment]
Closing as duplicate of #432
