### ISSUE TITLE
Plank preferences not available

### ISSUE THREAD

**Issue by donthomas21** [fedora-infra/fedora-packages#439]
Using Fedora 32 beta with cinannamon desktop I don't seem to have the ability to change the dock preferences.

PS. Filing a bug/comment is actually really tough. Most people would not get this far. Probably not a good thing, just a thought.

Don

**Comment by cverna** [comment]
Thanks for your report but this is however, the wrong place for such bug reports.

This issue tracker is about the web application running at: https://apps.fedoraproject.org/packages/

Your ticket should be opened on https://bugzilla.redhat.com
