### ISSUE TITLE
bootstrap.py missing dependencies

### ISSUE THREAD

**Issue by nanonyme** [fedora-infra/fedora-packages#58]
After installation I get an ImportError: No module named webhelpers.html when trying to run paster serve development.ini

**Comment by ralphbean** [comment]
FWIW, the instruction should be updated to tell you to use 'gearbox' instead of 'paster' now.

**Comment by TridevGuha** [comment]
which file need to be updated? @ralphbean

**Comment by ralphbean** [comment]
Check the README.

**Comment by ralphbean** [comment]
Fixed by @thunderoy.  Thanks!
