### ISSUE TITLE
Overview description not reflecting rpm side change

### ISSUE THREAD

**Issue by mtasaka** [fedora-infra/fedora-packages#66]
I was requested from the upstream developer to change the description of uget as https://bugzilla.redhat.com/show_bug.cgi?id=1055092 , so I changed the summary on rpm as http://pkgs.fedoraproject.org/cgit/uget.git/commit/?id=c8aa6d01802717636679b665e55a197200f3bb01 and the change was already pushed on F-21/20/19, however this change is not reflected on the description of https://apps.fedoraproject.org/packages/uget/overview/ .

**Comment by ralphbean** [comment]
I think this should be all fixed with the [latest release](http://threebean.org/blog/history-of-fedora-packages/).  Please re-open if you encounter further issues... and thanks so much for your patience.  :)
