### ISSUE TITLE
Recursion in link

### ISSUE THREAD

**Issue by tuxology** [fedora-infra/fedora-packages#71]
**Description**
Clicking the package hyperlink under `Builds` tab leads to unwanted recursion link

**Reproduction**
1. Go to https://apps.fedoraproject.org/packages/lttv
2. Click `Builds` tab
3. Click package name repeatedly
4. Resulting link is as follows -

`https://apps.fedoraproject.org/packages/lttv/undefined/packages//undefined/packages//undefined/packages//undefined/packages//undefined/packages//undefined/packages//undefined/packages//undefined/packages//undefined/packages//`

**Frequency of occurrence**
100%

**Use cases affected**
All (I have checked 7-8 packages)

**Related issues**
#45

**Comment by ralphbean** [comment]
Thanks.  I'm fairly sure this has been fixed now.  Please re-open if you notice it is not so.
