### ISSUE TITLE
Package -> Contents -> Spec is broken

### ISSUE THREAD

**Issue by ciupicri** [fedora-infra/fedora-packages#81]
The website doesn't show the [SPEC for Wordpress](https://apps.fedoraproject.org/packages/wordpress/sources/spec/). All I'm seeing is a list of patches.

**Comment by ralphbean** [comment]
This should be fixed as soon as we upgrade to python-tw2-core-2.2.2-3.el6.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
