### ISSUE TITLE
epel-release package is not found

### ISSUE THREAD

**Issue by ktdreyer** [fedora-infra/fedora-packages#89]
For some reason the "epel-release" package is not listed.

1. Look up [epel-release in pkgdb2](https://admin.fedoraproject.org/pkgdb/package/epel-release/).
2. Click the "Bug reports" link
3. The page shows "0 results"

(When searching in Bugzilla itself, there are [open bugs](https://bugzilla.redhat.com/buglist.cgi?component=epel-release&list_id=2486690&product=Fedora%20EPEL) on epel-release.)

It seems that packages has no knowledge of epel-release at all.

**Comment by ralphbean** [comment]
OK, [a rewrite is now deployed](http://threebean.org/blog/history-of-fedora-packages/) and this bug seems to be fixed.  Please open a new one if you notice things getting squirrely again.
