### ISSUE TITLE
Builds list does not link to koji

### ISSUE THREAD

**Issue by hhorak** [fedora-infra/fedora-packages#93]
I'm on https://apps.fedoraproject.org/packages/moin/builds/
and particular items in the build list are links, which should (imho) link to appropriate koji builds.
However, all links link to https://apps.fedoraproject.org/packages/package_maintenance/tools/builds?package=moin

**Comment by ralphbean** [comment]
The old links have been removed just yesterday.  Adding new links to point to koji makes sense.  We should do that, yes.
