### ISSUE TITLE
(Semi)newly added packages not found in packages app

### ISSUE THREAD

**Issue by scop** [fedora-infra/fedora-packages#98]
rpm-ostree-toolbox is missing from "packages" but it does exist. I've waited for 5 minutes as the caching note says, and it didn't appear.

https://apps.fedoraproject.org/packages/s/rpm-ostree-toolbox

http://koji.fedoraproject.org/koji/packageinfo?packageID=18594
http://pkgs.fedoraproject.org/cgit/rpm-ostree-toolbox.git/

**Comment by ralphbean** [comment]
OK, I think this should be all fixed with the [latest release](http://threebean.org/blog/history-of-fedora-packages/).  Please re-open if you encounter further issues... and thanks so much for your patience.  :)
