### ISSUE TITLE
Closed bugs information is wrong

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/fedora-packages#99]
I just wanted to know what bugs are open against fonttools in pkgdb2 which redirected me to https://apps.fedoraproject.org/packages/fonttools/bugs. Here I also find closed bugs link which when I clicked return zero results. I see the query constructed is wrong and checking for bugs closed after current time. 

I suppose that link is really for finding closed bugs against that package then we need fix for this?

**Comment by ralphbean** [comment]
Oh, wow!  You're right.  I wonder why we have that ``chfieldvalue`` argument in there.

I'll look at the git logs and ask some of the original designers.  If nothing comes up that makes sense, I'll just remove it.

**Comment by ralphbean** [comment]
Wow, looking further in to this.. it seems like the *number* on the page is supposed to be the number of bugs closed in the **last week**, but that isn't indicated anywhere on the page.

**Comment by ralphbean** [comment]
I'm just going to remove this feature, instead of fixing it.
